/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstd@sprivate@soscommon.nim.c.o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstd@sprivate@soscommon.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyTuple__IWVof32nvF9bSVI9atrGkyDw tyTuple__IWVof32nvF9bSVI9atrGkyDw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw;
struct tyTuple__IWVof32nvF9bSVI9atrGkyDw {
	tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw Field0;
	NIM_BOOL Field1;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[104+1];
} TM__ZrvRRRmaDcxlFjSFGlhGzQ_2 = { 104 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/oscommon.nim(76, 13) `path != \"\"` " };
static const NimStringV2 TM__ZrvRRRmaDcxlFjSFGlhGzQ_3 = {104, (NimStrPayload*)&TM__ZrvRRRmaDcxlFjSFGlhGzQ_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__IWVof32nvF9bSVI9atrGkyDw, getSymlinkFileKind__stdZprivateZoscommon_u17)(NimStringV2 path_p0) {
	tyTuple__IWVof32nvF9bSVI9atrGkyDw result;
	struct stat s_1;
	tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw colontmp_;
	NIM_BOOL colontmp__2;
NIM_BOOL* nimErr_;
	nimfr_("getSymlinkFileKind", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/oscommon.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__IWVof32nvF9bSVI9atrGkyDw));
	nimZeroMem((void*)(&s_1), sizeof(struct stat));
	nimlf_(76, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/oscommon.nim");	{
		if (!!(!((path_p0.len == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__ZrvRRRmaDcxlFjSFGlhGzQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(77);	colontmp_ = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)1);
	colontmp__2 = NIM_FALSE;
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	nimln_(78);	{
		int T7_;
		T7_ = (int)0;
		T7_ = stat(nimToCStringConv(path_p0), (&s_1));
		if (!(T7_ == ((NI32)0))) goto LA8_;
		nimln_(79);		{
			NIM_BOOL T12_;
			tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw colontmp__3;
			NIM_BOOL colontmp__4;
			T12_ = (NIM_BOOL)0;
			T12_ = S_ISDIR(s_1.st_mode);
			if (!T12_) goto LA13_;
			nimln_(80);			colontmp__3 = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)3);
			colontmp__4 = NIM_FALSE;
			result.Field0 = colontmp__3;
			result.Field1 = colontmp__4;
		}
		goto LA10_;
LA13_: ;
		{
			NIM_BOOL T16_;
			tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw colontmp__5;
			NIM_BOOL colontmp__6;
			nimln_(81);			T16_ = (NIM_BOOL)0;
			T16_ = S_ISREG(s_1.st_mode);
			if (!!(T16_)) goto LA17_;
			nimln_(82);			colontmp__5 = ((tyEnum_PathComponent__yW9b9aNI9azCXjH1pLbEHvwMw)1);
			colontmp__6 = NIM_TRUE;
			result.Field0 = colontmp__5;
			result.Field1 = colontmp__6;
		}
		goto LA10_;
LA17_: ;
LA10_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0) {
	NIM_BOOL result;
	struct stat res_1;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("dirExists", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/oscommon.nim");
	nimZeroMem((void*)(&res_1), sizeof(struct stat));
	nimln_(143);	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(dir_p0), (&res_1));
	T1_ = (((NI32)0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISDIR(res_1.st_mode);
LA3_: ;
	result = T1_;
	popFrame();
	return result;
}
