/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstreams.nim.c.o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstreams.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__Xl32m0kTaH9ahJZb5rqVy6w) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ooJWa8lnlfnobNqxEOtnNA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__E19bfDo0XX9btMFiY2C0tGGg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qvufjYFbEQ9cqXk4e8pAzJQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__wBfXfmCdEwRLtDI7TCPoAQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ohJ27oJZLprJ3hzTGNCkpA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qcX1k0ZWyDvPcQjruoqTPg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__E6HHS1dkEvJbg7JG3Yyt9ag) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg {
	RootObj Sup;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w closeImpl;
	tyProc__ooJWa8lnlfnobNqxEOtnNA atEndImpl;
	tyProc__E19bfDo0XX9btMFiY2C0tGGg setPositionImpl;
	tyProc__qvufjYFbEQ9cqXk4e8pAzJQ getPositionImpl;
	tyProc__wBfXfmCdEwRLtDI7TCPoAQ readDataStrImpl;
	tyProc__ohJ27oJZLprJ3hzTGNCkpA readLineImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg readDataImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg peekDataImpl;
	tyProc__E6HHS1dkEvJbg7JG3Yyt9ag writeDataImpl;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w flushImpl;
};
struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u221)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u212)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_2 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_3 = {1, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u212)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
NIM_BOOL* nimErr_;
	nimfr_("writeData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(348, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	(*s_p0).writeDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u221)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2 x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(381);	{
		if (!(((NI)0) < x_p1.len)) goto LA3_;
		nimln_(386);		writeData__pureZstreams_u212(s_p0, ((void*) (nimToCStringConv(x_p1))), x_p1.len);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, writeLine__pureZstreams_u231)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* args_p1, NI args_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("writeLine", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* str_1;
		NI i_1;
		str_1 = (NimStringV2*)0;
		nimlf_(18, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_1 < args_p1Len_0)) goto LA3;
				nimlf_(411, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");				if (i_1 < 0 || i_1 >= args_p1Len_0){ raiseIndexError2(i_1,args_p1Len_0-1); goto BeforeRet_;
				}
				str_1 = (&args_p1[i_1]);
				write__pureZstreams_u221(s_p0, (*str_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(412, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	write__pureZstreams_u221(s_p0, TM__Ue7tnBcsL67VCiRfvt8q0A_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
