/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstd@sprivate@sospaths2.nim.c.o /Users/nakagawa_shota/repo/valit/crown/nimcache_quick/@pstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <unistd.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg {
	NI i;
	NI prev;
	NIM_BOOL notFirst;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, normalizePathAux__stdZprivateZospaths2_u15)(NimStringV2* path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nosnormalizePath)(NimStringV2* path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2731)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizePath__pureZpathnorm_u150)(NimStringV2 path_p0, NIM_CHAR dirSep_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePathInternal__stdZprivateZospaths2_u18)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePath__stdZprivateZospaths2_u359)(NimStringV2 path_p0, NimStringV2 root_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8541)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8593)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u86)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u9070)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasNext__pureZpathnorm_u6)(tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg it_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, next__pureZpathnorm_u10)(tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg* it_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(void, nossplitPath)(NimStringV2 path_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9118)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9131)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2722)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZospaths2_u303)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_3 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_4 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_5 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_4};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_6 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
extern TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_7 = { 36 | NIM_STRLIT_FLAG, "The specified root is not absolute: " };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_8 = {36, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_7};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_17 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_18 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_17};
static const struct {
  NI cap; NIM_CHAR data[107+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_19 = { 107 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim(885, 21) `bufsize >= 0` " };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_20 = {107, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_19};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_21 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_28 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_29 = {2, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_28};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_33 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_4};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_35 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_40 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static NIM_CONST tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ TM__O1zDbSYyG8zQytyoZAh0dg_22 = {((NI)0),
((NI)-1)}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nosnormalizePath)(NimStringV2* path_p0) {
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("normalizePath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	nimlf_(932, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = normalizePath__pureZpathnorm_u150((*path_p0), 47);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T1_); goto BeforeRet_;}
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqsink___system_u2731((&(*path_p0)), T1_);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, normalizePathAux__stdZprivateZospaths2_u15)(NimStringV2* path_p0) {
NIM_BOOL* nimErr_;
	nimfr_("normalizePathAux", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nosnormalizePath(path_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0) {
	NIM_BOOL result;
	nimfr_("isAbsolute", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{	nimlf_(244, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	{
		if (!(path_p0.len == ((NI)0))) goto LA3_;
		nimln_(232);		nimln_(244);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(256);	if (((NI)0) < 0 || ((NI)0) >= path_p0.len){ raiseIndexError2(((NI)0),path_p0.len-1); goto BeforeRet_;
	}
	result = ((NU8)(path_p0.p->data[((NI)0)]) == (NU8)(47));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u8541)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_10;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");
{	result = (NIM_CHAR)0;
	if (nimSubInt(s_p0.len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10) >= s_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10),s_p0.len-1); goto BeforeRet_;
	}
	result = s_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8593)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_11;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s_p0)));
	if (nimSubInt((*s_p0).len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11) >= (*s_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11),(*s_p0).len-1); goto BeforeRet_;
	}
	result = (&(*s_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i_1;
	nimfr_("normalizePathEnd", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{	nimln_(51);	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(52);	i_1 = (*path_p0).len;
	{
		nimln_(53);		while (1) {
			if (!(((NI)1) <= i_1)) goto LA6;
			nimln_(54);			{
				NI TM__O1zDbSYyG8zQytyoZAh0dg_12;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_13;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_12)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12),(*path_p0).len-1); goto BeforeRet_;
				}
				if (!(((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12)])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12)])) == ((NU8)(47)))) goto LA9_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_13)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_14;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_15;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_16;
				nimln_(55);				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_14)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_14) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_14) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_14),(*path_p0).len-1); goto BeforeRet_;
				}
				T13_ = ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_14)]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i_1);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				if (nimSubInt(i_1, ((NI)2), &TM__O1zDbSYyG8zQytyoZAh0dg_15)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15),(*path_p0).len-1); goto BeforeRet_;
				}
				T12_ = (((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15)])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15)])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_16)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16);
			}
			goto LA7_;
LA16_: ;
			{
				nimln_(56);				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	nimln_(57);	{
		if (!trailingSep_p1) goto LA21_;
		nimln_(59);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
		nimln_(61);		nimAddCharV1((&(*path_p0)), 47);
	}
	goto LA19_;
LA21_: ;
	{
		nimln_(62);		if (!(((NI)0) < i_1)) goto LA24_;
		nimln_(64);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
	}
	goto LA19_;
LA24_: ;
	{
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_18);
	}
LA19_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep_1;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
	nimfr_("joinPathImpl", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(85, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	nimln_(82);	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8541(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(47)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	nimln_(85);	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	nimln_(82);	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8593(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(47)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep_1 = T1_;
	nimln_(86);	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(87);	addNormalizePath__pureZpathnorm_u86(tail_p2, result_p0, state_p1, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, trailingSep_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_9;
	NI state_1;
NIM_BOOL* nimErr_;
	nimfr_("joinPath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(116);	if (nimAddInt(head_p0.len, tail_p1.len, &TM__O1zDbSYyG8zQytyoZAh0dg_9)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9)) < ((NI)0) || ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9)));
	nimln_(117);	state_1 = ((NI)0);
	nimln_(118);	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state_1), head_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(119);	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state_1), tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePath__stdZprivateZospaths2_u359)(NimStringV2 path_p0, NimStringV2 root_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("absolutePath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	nimln_(901);	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = nosisAbsolute(path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T4_) goto LA5_;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqcopy___system_u2725((&result), path_p0);
	}
	goto LA2_;
LA5_: ;
	{
		nimlf_(903, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		{
			NIM_BOOL T10_;
			tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T13_;
			NimStringV2 T14_;
			T10_ = (NIM_BOOL)0;
			T10_ = nosisAbsolute(root_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T10_)) goto LA11_;
			T13_ = NIM_NIL;
			T13_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
			(*T13_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
			(*T13_).Sup.Sup.name = "ValueError";
			nimln_(904);			T14_.len = 0; T14_.p = NIM_NIL;
			T14_ = rawNewString(root_p1.len + 36);
appendString((&T14_), TM__O1zDbSYyG8zQytyoZAh0dg_8);
appendString((&T14_), root_p1);
			(*T13_).Sup.Sup.message = T14_;
			(*T13_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T13_, "ValueError", "absolutePath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim", 904);
goto BeforeRet_;
		}
LA11_: ;
		nimln_(890);		nimln_(905);		result = nosjoinPath(root_p1, path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u9070)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	nimlf_(2772, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2773);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2774);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void) {
	NimStringV2 result;
	NI bufsize_1;
NIM_BOOL* nimErr_;
	nimfr_("getCurrentDir", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(875, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	bufsize_1 = ((NI)1024);
	nimln_(876);	if ((bufsize_1) < ((NI)0) || (bufsize_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufsize_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((bufsize_1));
	{
		nimln_(877);		while (1) {
			nimln_(878);			{
				NCSTRING T5_;
				NIM_BOOL T6_;
				size_t T9_;
				T5_ = (NCSTRING)0;
				T5_ = getcwd(nimToCStringConv(result), bufsize_1);
				T6_ = (NIM_BOOL)0;
				T6_ = eqeq___system_u9070(T5_, ((NCSTRING) NIM_NIL));
				if (!!(T6_)) goto LA7_;
				nimln_(879);				T9_ = (size_t)0;
				T9_ = strlen(nimToCStringConv(result));
				if (T9_ > (size_t)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI) (T9_)));
				nimln_(880);				goto LA1;
			}
			goto LA3_;
LA7_: ;
			{
				NI32 err_1;
				nimln_(882);				err_1 = osLastError__stdZoserrors_u122();
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(883);				{
					NimStringV2 T19_;
					if (!(err_1 == ERANGE)) goto LA13_;
					nimln_(884);					bufsize_1 = (NI)((NU64)(bufsize_1) << (NU64)(((NI)1) & (64 - 1)));
					nimln_(885);					{
						if (!!((((NI)0) <= bufsize_1))) goto LA17_;
						failedAssertImpl__stdZassertions_u95(TM__O1zDbSYyG8zQytyoZAh0dg_20);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA17_: ;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					nimlf_(886, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");					if ((bufsize_1) < ((NI)0) || (bufsize_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufsize_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
					}
					T19_.len = 0; T19_.p = NIM_NIL;
					T19_ = mnewString((bufsize_1));
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					eqsink___system_u2731((&result), T19_);
				}
				goto LA11_;
LA13_: ;
				{
					NI32 T21_;
					nimlf_(888, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");					T21_ = (NI32)0;
					T21_ = osLastError__stdZoserrors_u122();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					raiseOSError__stdZoserrors_u119(T21_, TM__O1zDbSYyG8zQytyoZAh0dg_21);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA11_: ;
			}
LA3_: ;
		}
	} LA1: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePathInternal__stdZprivateZospaths2_u18)(NimStringV2 path_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("absolutePathInternal", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(908);	nimln_(890);	colontmpD_ = nosgetCurrentDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(908);	result = absolutePath__stdZprivateZospaths2_u359(path_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosrelativePath)(NimStringV2 path_p0, NimStringV2 base_p1, NIM_CHAR sep_p2) {
	NimStringV2 result;
	NimStringV2 base_2;
	NimStringV2 path_2;
	NimStringV2 T6_;
	NIM_BOOL a1_1;
	NIM_BOOL a2_1;
	tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg f_1;
	tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg b_1;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ ff_1;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ bb_1;
NIM_BOOL* nimErr_;
	nimfr_("relativePath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	base_2.len = 0; base_2.p = NIM_NIL;
	path_2.len = 0; path_2.p = NIM_NIL;
	nimlf_(317, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	{
		if (!(path_p0.len == ((NI)0))) goto LA4_;
		nimln_(291);		nimln_(317);		result = TM__O1zDbSYyG8zQytyoZAh0dg_3;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (path_2.p && !(path_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_2.p);
}
		if (base_2.p && !(base_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(base_2.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	T6_.len = 0; T6_.p = NIM_NIL;
	nimlf_(318, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	{
		if (!eqStrings(base_p1, TM__O1zDbSYyG8zQytyoZAh0dg_5)) goto LA9_;
		base_2 = TM__O1zDbSYyG8zQytyoZAh0dg_6;
	}
	goto LA7_;
LA9_: ;
	{
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqcopy___system_u2725((&base_2), base_p1);
	}
LA7_: ;
	eqcopy___system_u2725((&path_2), path_p0);
	nimlf_(320, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	normalizePathAux__stdZprivateZospaths2_u15((&path_2));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(321);	normalizePathAux__stdZprivateZospaths2_u15((&base_2));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(322);	a1_1 = nosisAbsolute(path_2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(323);	a2_1 = nosisAbsolute(base_2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(324);	{
		NIM_BOOL T14_;
		NimStringV2 T18_;
		T14_ = (NIM_BOOL)0;
		T14_ = a1_1;
		if (!(T14_)) goto LA15_;
		T14_ = !(a2_1);
LA15_: ;
		if (!T14_) goto LA16_;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		nimlf_(325, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		T18_.len = 0; T18_.p = NIM_NIL;
		T18_ = absolutePathInternal__stdZprivateZospaths2_u18(base_2);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T18_); goto LA1_;}
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&base_2), T18_);
	}
	goto LA12_;
LA16_: ;
	{
		NIM_BOOL T20_;
		NimStringV2 T24_;
		nimlf_(326, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		T20_ = (NIM_BOOL)0;
		T20_ = a2_1;
		if (!(T20_)) goto LA21_;
		T20_ = !(a1_1);
LA21_: ;
		if (!T20_) goto LA22_;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		nimlf_(327, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		T24_.len = 0; T24_.p = NIM_NIL;
		T24_ = absolutePathInternal__stdZprivateZospaths2_u18(path_2);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T24_); goto LA1_;}
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&path_2), T24_);
	}
	goto LA12_;
LA22_: ;
LA12_: ;
	nimlf_(334, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	nimZeroMem((void*)(&f_1), sizeof(tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg));
	nimln_(335);	nimZeroMem((void*)(&b_1), sizeof(tyObject_PathIter__plw2s0llOMWOSkDXmW2PKg));
	nimln_(336);	ff_1 = TM__O1zDbSYyG8zQytyoZAh0dg_22;
	nimln_(337);	bb_1 = TM__O1zDbSYyG8zQytyoZAh0dg_22;
	nimln_(338);	if ((path_2.len) < ((NI)0) || (path_2.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(path_2.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	result = rawNewString((path_2.len));
	{
		nimln_(340);		while (1) {
			NIM_BOOL T27_;
			NI diff_1;
			NI TM__O1zDbSYyG8zQytyoZAh0dg_23;
			NIM_BOOL same_1;
			NI colontmp_;
			NI colontmp__2;
			NI colontmp__3;
			NI colontmp__4;
			T27_ = (NIM_BOOL)0;
			T27_ = hasNext__pureZpathnorm_u6(f_1, path_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			if (!(T27_)) goto LA28_;
			T27_ = hasNext__pureZpathnorm_u6(b_1, base_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
LA28_: ;
			if (!T27_) goto LA26;
			nimln_(341);			ff_1 = next__pureZpathnorm_u10((&f_1), path_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			nimln_(342);			bb_1 = next__pureZpathnorm_u10((&b_1), base_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			nimln_(343);			if (nimSubInt(ff_1.Field1, ff_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_23)) { raiseOverflow(); goto LA1_;
			};
			diff_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_23);
			nimln_(344);			{
				NI TM__O1zDbSYyG8zQytyoZAh0dg_24;
				if (nimSubInt(bb_1.Field1, bb_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_24)) { raiseOverflow(); goto LA1_;
				};
				if (!!((diff_1 == (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_24)))) goto LA31_;
				goto LA25;
			}
LA31_: ;
			nimln_(345);			same_1 = NIM_TRUE;
			{
				NI i_1;
				NI res_1;
				i_1 = (NI)0;
				nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				res_1 = ((NI)0);
				{
					nimln_(97);					while (1) {
						NI TM__O1zDbSYyG8zQytyoZAh0dg_27;
						if (!(res_1 <= diff_1)) goto LA35;
						nimlf_(346, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");						i_1 = ((NI) (res_1));
						nimln_(347);						{
							NI TM__O1zDbSYyG8zQytyoZAh0dg_25;
							NIM_CHAR T38_;
							NI TM__O1zDbSYyG8zQytyoZAh0dg_26;
							NIM_CHAR T39_;
							nimln_(265);							nimln_(347);							if (nimAddInt(i_1, ff_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_25)) { raiseOverflow(); goto LA1_;
							};
							if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_25) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_25) >= path_2.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_25),path_2.len-1); goto LA1_;
							}
							nimln_(265);							T38_ = (NIM_CHAR)0;
							T38_ = nsuToLowerAsciiChar(path_2.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_25)]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
							nimln_(347);							if (nimAddInt(i_1, bb_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_26)) { raiseOverflow(); goto LA1_;
							};
							if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_26) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_26) >= base_2.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_26),base_2.len-1); goto LA1_;
							}
							nimln_(265);							T39_ = (NIM_CHAR)0;
							T39_ = nsuToLowerAsciiChar(base_2.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_26)]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
							if (!!(((NU8)(T38_) == (NU8)(T39_)))) goto LA40_;
							nimln_(348);							same_1 = NIM_FALSE;
							nimln_(349);							goto LA33;
						}
LA40_: ;
						nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");						if (nimAddInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_27)) { raiseOverflow(); goto LA1_;
						};
						res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_27);
					} LA35: ;
				}
			} LA33: ;
			nimlf_(350, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");			{
				if (!!(same_1)) goto LA44_;
				goto LA25;
			}
LA44_: ;
			nimln_(351);			colontmp_ = ((NI)0);
			colontmp__2 = ((NI)-1);
			ff_1.Field0 = colontmp_;
			ff_1.Field1 = colontmp__2;
			nimln_(352);			colontmp__3 = ((NI)0);
			colontmp__4 = ((NI)-1);
			bb_1.Field0 = colontmp__3;
			bb_1.Field1 = colontmp__4;
		} LA26: ;
	} LA25: ;
	{
		nimln_(360);		while (1) {
			nimln_(361);			{
				if (!(bb_1.Field0 <= bb_1.Field1)) goto LA50_;
				nimln_(362);				{
					NIM_BOOL T54_;
					NIM_CHAR* T56_;
					T54_ = (NIM_BOOL)0;
					T54_ = (((NI)0) < result.len);
					if (!(T54_)) goto LA55_;
					T56_ = (NIM_CHAR*)0;
					T56_ = X5BX5D___system_u8593((&result), ((NI)1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					T54_ = !(((NU8)((*T56_)) == (NU8)(sep_p2)));
LA55_: ;
					if (!T54_) goto LA57_;
					nimln_(363);					nimAddCharV1((&result), sep_p2);
				}
LA57_: ;
				nimln_(364);				prepareAdd((&result), 2);
appendString((&result), TM__O1zDbSYyG8zQytyoZAh0dg_29);
			}
LA50_: ;
			nimln_(365);			{
				NIM_BOOL T61_;
				T61_ = (NIM_BOOL)0;
				T61_ = hasNext__pureZpathnorm_u6(b_1, base_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!!(T61_)) goto LA62_;
				goto LA46;
			}
LA62_: ;
			nimln_(366);			bb_1 = next__pureZpathnorm_u10((&b_1), base_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA46: ;
	{
		nimln_(369);		while (1) {
			nimln_(370);			{
				if (!(ff_1.Field0 <= ff_1.Field1)) goto LA68_;
				nimln_(371);				{
					NIM_BOOL T72_;
					NIM_CHAR* T74_;
					T72_ = (NIM_BOOL)0;
					T72_ = (((NI)0) < result.len);
					if (!(T72_)) goto LA73_;
					T74_ = (NIM_CHAR*)0;
					T74_ = X5BX5D___system_u8593((&result), ((NI)1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					T72_ = !(((NU8)((*T74_)) == (NU8)(sep_p2)));
LA73_: ;
					if (!T72_) goto LA75_;
					nimln_(372);					nimAddCharV1((&result), sep_p2);
				}
LA75_: ;
				{
					NI i_2;
					NI colontmp__5;
					NI TM__O1zDbSYyG8zQytyoZAh0dg_30;
					NI res_2;
					i_2 = (NI)0;
					colontmp__5 = (NI)0;
					nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					nimlf_(373, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");					if (nimSubInt(ff_1.Field1, ff_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_30)) { raiseOverflow(); goto LA1_;
					};
					colontmp__5 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_30);
					nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					res_2 = ((NI)0);
					{
						nimln_(97);						while (1) {
							NI TM__O1zDbSYyG8zQytyoZAh0dg_31;
							NI TM__O1zDbSYyG8zQytyoZAh0dg_32;
							if (!(res_2 <= colontmp__5)) goto LA79;
							nimlf_(373, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");							i_2 = ((NI) (res_2));
							nimln_(374);							if (nimAddInt(i_2, ff_1.Field0, &TM__O1zDbSYyG8zQytyoZAh0dg_31)) { raiseOverflow(); goto LA1_;
							};
							if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_31) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_31) >= path_2.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_31),path_2.len-1); goto LA1_;
							}
							nimAddCharV1((&result), path_2.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_31)]);
							nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");							if (nimAddInt(res_2, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_32)) { raiseOverflow(); goto LA1_;
							};
							res_2 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_32);
						} LA79: ;
					}
				}
			}
LA68_: ;
			nimlf_(375, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");			{
				NIM_BOOL T82_;
				T82_ = (NIM_BOOL)0;
				T82_ = hasNext__pureZpathnorm_u6(f_1, path_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!!(T82_)) goto LA83_;
				goto LA64;
			}
LA83_: ;
			nimln_(376);			ff_1 = next__pureZpathnorm_u10((&f_1), path_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA64: ;
	nimln_(379);	{
		if (!(result.len == ((NI)0))) goto LA87_;
		prepareAdd((&result), 1);
appendString((&result), TM__O1zDbSYyG8zQytyoZAh0dg_33);
	}
LA87_: ;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (path_2.p && !(path_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_2.p);
}
		if (base_2.p && !(base_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(base_2.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nossplitPath)(NimStringV2 path_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result) {
	NI sepPos_1;
	nimfr_("splitPath", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{	nimZeroMem((void*)Result, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
	nimlf_(211, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	sepPos_1 = ((NI)-1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_36;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(6, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(212, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		if (nimSubInt(path_p0.len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_36)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_36);
		nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = colontmp_;
		{
			nimln_(34);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_37;
				if (!(((NI)0) <= res_1)) goto LA3;
				nimlf_(212, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");				i_1 = ((NI) (res_1));
				nimln_(213);				{
					if (i_1 < 0 || i_1 >= path_p0.len){ raiseIndexError2(i_1,path_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA6_;
					nimln_(214);					sepPos_1 = i_1;
					nimln_(215);					goto LA1;
				}
LA6_: ;
				nimlf_(39, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimSubInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_37)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_37);
			} LA3: ;
		}
	} LA1: ;
	nimlf_(216, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	{
		NI colontmpD_;
		NI colontmpD__2;
		NI T12_;
		NimStringV2 T19_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_39;
		NimStringV2 T20_;
		if (!(((NI)0) <= sepPos_1)) goto LA10_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		nimlf_(217, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		T12_ = (NI)0;
		nimln_(221);		{
			NIM_BOOL T15_;
			NI TM__O1zDbSYyG8zQytyoZAh0dg_38;
			nimlf_(2067, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			nimlf_(221, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");			nimlf_(2067, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			T15_ = (NIM_BOOL)0;
			T15_ = NIM_LIKELY((((NI)1) <= sepPos_1));
			if (!T15_) goto LA16_;
			nimlf_(221, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");			if (nimSubInt(sepPos_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_38)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmpD_ = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_38);
			T12_ = colontmpD_;
		}
		goto LA13_;
LA16_: ;
		{
			colontmpD__2 = ((NI)0);
			T12_ = colontmpD__2;
		}
LA13_: ;
		nimln_(217);		T19_.len = 0; T19_.p = NIM_NIL;
		T19_ = substr__system_u9118(path_p0, ((NI)0), T12_);
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&(*Result).Field0), T19_);
		nimlf_(223, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		if (nimAddInt(sepPos_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_39)) { raiseOverflow(); goto BeforeRet_;
		};
		T20_.len = 0; T20_.p = NIM_NIL;
		T20_ = substr__system_u9131(path_p0, (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_39));
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&(*Result).Field1), T20_);
	}
	goto LA8_;
LA10_: ;
	{
		eqsink___system_u2731((&(*Result).Field0), TM__O1zDbSYyG8zQytyoZAh0dg_40);
		eqcopy___system_u2725((&(*Result).Field1), path_p0);
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZospaths2_u303)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosextractFilename)(NimStringV2 path_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("extractFilename", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(684, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	{
		NIM_BOOL T3_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_34;
		T3_ = (NIM_BOOL)0;
		T3_ = (path_p0.len == ((NI)0));
		if (T3_) goto LA4_;
		if (nimSubInt(path_p0.len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_34)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_34) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_34) >= path_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_34),path_p0.len-1); goto BeforeRet_;
		}
		T3_ = (((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_34)])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_34)])) == ((NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(685);		result = TM__O1zDbSYyG8zQytyoZAh0dg_35;
	}
	goto LA1_;
LA5_: ;
	{
		tyTuple__UV3llMMYFckfui8YMBuUZA colontmpD_;
		nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
		nimln_(687);		nossplitPath(path_p0, (&colontmpD_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_.Field1;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqwasMoved___system_u2722((&colontmpD_.Field1));
		nimlf_(687, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");		eqdestroy___stdZprivateZospaths2_u303((&colontmpD_));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
