/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@mcrown_test_env.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@mcrown_test_env.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, putEnv__stdZenvvars_u23)(NimStringV2 key_p0, NimStringV2 val_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__LYQfT4t41Dx9aow4b57ReXg_2 = { 10 | NIM_STRLIT_FLAG, "SECRET_KEY" };
static const NimStringV2 TM__LYQfT4t41Dx9aow4b57ReXg_3 = {10, (NimStrPayload*)&TM__LYQfT4t41Dx9aow4b57ReXg_2};
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__LYQfT4t41Dx9aow4b57ReXg_4 = { 37 | NIM_STRLIT_FLAG, "crown-test-secret-key-32chars-min____" };
static const NimStringV2 TM__LYQfT4t41Dx9aow4b57ReXg_5 = {37, (NimStrPayload*)&TM__LYQfT4t41Dx9aow4b57ReXg_4};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atmcrown_test_envdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("crown_test_env", "/Users/nakagawa_shota/repo/valit/crown/tests/crown_test_env.nim");
nimErr_ = nimErrorFlag();
	nimlf_(4, "/Users/nakagawa_shota/repo/valit/crown/tests/crown_test_env.nim");	putEnv__stdZenvvars_u23(TM__LYQfT4t41Dx9aow4b57ReXg_3, TM__LYQfT4t41Dx9aow4b57ReXg_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

