/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@senv.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@senv.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA;
typedef struct tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg;
typedef struct tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg;
typedef struct tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg;
typedef struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA;
typedef struct tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA {
	RootObj Sup;
	NI bufpos;
	NimStringV2 buf;
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__7nmFzAY8WAArf5RvWTtaQA;
struct tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg {
	tyEnum_TokKind__7nmFzAY8WAArf5RvWTtaQA kind;
	NimStringV2 literal;
};
struct tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg {
	tyObject_BaseLexer__7FdE9b68RVRykP6bGRTSliA Sup;
	tyObject_Token__RxDmtd7v9cVJshCnqQq1Idg tok;
	NimStringV2 filename;
};
typedef N_NIMCALL_PTR(void, tyProc__Xl32m0kTaH9ahJZb5rqVy6w) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ooJWa8lnlfnobNqxEOtnNA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__E19bfDo0XX9btMFiY2C0tGGg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qvufjYFbEQ9cqXk4e8pAzJQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__wBfXfmCdEwRLtDI7TCPoAQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ohJ27oJZLprJ3hzTGNCkpA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qcX1k0ZWyDvPcQjruoqTPg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__E6HHS1dkEvJbg7JG3Yyt9ag) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg {
	RootObj Sup;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w closeImpl;
	tyProc__ooJWa8lnlfnobNqxEOtnNA atEndImpl;
	tyProc__E19bfDo0XX9btMFiY2C0tGGg setPositionImpl;
	tyProc__qvufjYFbEQ9cqXk4e8pAzJQ getPositionImpl;
	tyProc__wBfXfmCdEwRLtDI7TCPoAQ readDataStrImpl;
	tyProc__ohJ27oJZLprJ3hzTGNCkpA readLineImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg readDataImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg peekDataImpl;
	tyProc__E6HHS1dkEvJbg7JG3Yyt9ag writeDataImpl;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w flushImpl;
};
struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA {
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg Sup;
	FILE* f;
};
typedef NU8 tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA;
typedef NimStringV2 tyArray__dyW7vpmfeTYw8kX3EXuaJA[3];
typedef NU8 tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw;
struct tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ {
	RootObj Sup;
	tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw kind;
union{
	struct {
	NimStringV2 section;
} _kind_2;
	struct {
	NimStringV2 key;
	NimStringV2 value;
} _kind_3;
	struct {
	NimStringV2 msg;
} _kind_4;
};
};
struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(void, loadDotEnv__pkgZbasolatoZcoreZenv_u11)(NimStringV2 path_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u62)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u1093)(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*, newFileStream__pureZstreams_u1210)(NimStringV2 filename_p0, tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA mode_p1, NI bufSize_p2);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* c_p0, tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* input_p1, NimStringV2 filename_p2, NI lineOffset_p3);
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* c_p0, tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_u447)(tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, putEnv__stdZenvvars_u23)(NimStringV2 key_p0, NimStringV2 val_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZparsecfg_u22)(tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg* c_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern TNimTypeV2 NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_;
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__fh7E9aekaPaNEVuD4v7HR8Q_2 = { 27 | NIM_STRLIT_FLAG, "Basolato uses config file \'" };
static const NimStringV2 TM__fh7E9aekaPaNEVuD4v7HR8Q_3 = {27, (NimStrPayload*)&TM__fh7E9aekaPaNEVuD4v7HR8Q_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__fh7E9aekaPaNEVuD4v7HR8Q_4 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__fh7E9aekaPaNEVuD4v7HR8Q_5 = {1, (NimStrPayload*)&TM__fh7E9aekaPaNEVuD4v7HR8Q_4};
extern TNimTypeV2 NTIv2__xinZeGTaQCxxN1TGrWYliQ_;
static const struct {
  NI cap; NIM_CHAR data[64+1];
} TM__fh7E9aekaPaNEVuD4v7HR8Q_6 = { 64 | NIM_STRLIT_FLAG, "field \'key\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__fh7E9aekaPaNEVuD4v7HR8Q_7 = {64, (NimStrPayload*)&TM__fh7E9aekaPaNEVuD4v7HR8Q_6};
static const struct {
  NI cap; NIM_CHAR data[66+1];
} TM__fh7E9aekaPaNEVuD4v7HR8Q_8 = { 66 | NIM_STRLIT_FLAG, "field \'value\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__fh7E9aekaPaNEVuD4v7HR8Q_9 = {66, (NimStrPayload*)&TM__fh7E9aekaPaNEVuD4v7HR8Q_8};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__fh7E9aekaPaNEVuD4v7HR8Q_10 = { 4 | NIM_STRLIT_FLAG, ".env" };
static const NimStringV2 TM__fh7E9aekaPaNEVuD4v7HR8Q_11 = {4, (NimStrPayload*)&TM__fh7E9aekaPaNEVuD4v7HR8Q_10};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, loadDotEnv__pkgZbasolatoZcoreZenv_u11)(NimStringV2 path_p0) {
	tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* file_1;
	tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg parser_1;
	tyArray__dyW7vpmfeTYw8kX3EXuaJA T11_;
NIM_BOOL* nimErr_;
	nimfr_("loadDotEnv", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");
{nimErr_ = nimErrorFlag();
	file_1 = NIM_NIL;
	nimZeroMem((void*)(&parser_1), sizeof(tyObject_CfgParser__xKGlcBiu2pA13Poy9c49b9ayg));
	parser_1.Sup.Sup.m_type = (&NTIv2__xKGlcBiu2pA13Poy9c49b9ayg_);
	nimlf_(13, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = nosfileExists(path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		nimln_(14);		nimlf_(230, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");		eqdestroy___pureZparsecfg_u62((&parser_1));
		nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");		eqdestroy___pureZstreams_u1093(file_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(16, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");	file_1 = newFileStream__pureZstreams_u1210(path_p0, ((tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(17);	{
		if (!(file_1 == 0)) goto LA9_;
		nimln_(18);		nimlf_(230, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");		eqdestroy___pureZparsecfg_u62((&parser_1));
		nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");		eqdestroy___pureZstreams_u1093(file_1);
		goto BeforeRet_;
	}
LA9_: ;
	nimlf_(20, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");	T11_[0] = TM__fh7E9aekaPaNEVuD4v7HR8Q_3;
	T11_[1] = path_p0;
	T11_[2] = TM__fh7E9aekaPaNEVuD4v7HR8Q_5;
	echoBinSafe(T11_, 3);
	nimln_(23);	npcopen((&parser_1), (*((tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg**) (&(file_1)))), path_p0, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(24);		while (1) {
			tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ entry_1;
			nimZeroMem((void*)(&entry_1), sizeof(tyObject_CfgEvent__xinZeGTaQCxxN1TGrWYliQ));
			entry_1.Sup.m_type = (&NTIv2__xinZeGTaQCxxN1TGrWYliQ_);
			nimln_(25);			npcnext((&parser_1), (&entry_1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
			nimln_(26);			switch (entry_1.kind) {
			case ((tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw)0):
			{
				nimlf_(453, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");				eqdestroy___pureZparsecfg_u447((&entry_1));
				nimlf_(28, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");				goto LA12;
			}
			break;
			case ((tyEnum_CfgEventKind__689cCUjw6Z29atEmyF9angXSw)2):
			{
				nimln_(30);				if (!(((12 &((NU8)1<<((NU)((entry_1.kind))&7U)))!=0))) 				{ raiseFieldErrorStr(TM__fh7E9aekaPaNEVuD4v7HR8Q_7, dollar___pureZparsecfg_u22(entry_1.kind)); goto LA14_;
				}
				if (!(((12 &((NU8)1<<((NU)((entry_1.kind))&7U)))!=0))) 				{ raiseFieldErrorStr(TM__fh7E9aekaPaNEVuD4v7HR8Q_9, dollar___pureZparsecfg_u22(entry_1.kind)); goto LA14_;
				}
				putEnv__stdZenvvars_u23(entry_1._kind_3.key, entry_1._kind_3.value);
				if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
			}
			break;
			default:
			{
			}
			break;
			}
			{
				LA14_:;
			}
			{
				nimlf_(453, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");				eqdestroy___pureZparsecfg_u447((&entry_1));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA12: ;
	nimlf_(33, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");	npcclose((&parser_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(230, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parsecfg.nim");		eqdestroy___pureZparsecfg_u62((&parser_1));
		nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");		eqdestroy___pureZstreams_u1093(file_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(178, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atnbasolatominus0dot16dot1minus4f54fe4f58a388e25fe3d4c11176176b02418f99atsbasolatoatscoreatsenvdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("env", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");
nimErr_ = nimErrorFlag();
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimlf_(37, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");		nimln_(12);		colontmpD_ = nosgetCurrentDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		colontmpD__2 = slash___stdZprivateZospaths2_u88(colontmpD_, TM__fh7E9aekaPaNEVuD4v7HR8Q_11);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		nimln_(37);		loadDotEnv__pkgZbasolatoZcoreZenv_u11(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

