/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@ssettings.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@ssettings.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_2 = { 10 | NIM_STRLIT_FLAG, "SECRET_KEY" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_3 = {10, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_5 = {0, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_4};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__bSUSYdX7Li9cqJDbeYzoJAw_6 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
static const struct {
  NI cap; NIM_CHAR data[49+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_7 = { 49 | NIM_STRLIT_FLAG, "SECRET_KEY is not defined in environment variable" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_8 = {49, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_7};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_9 = { 6 | NIM_STRLIT_FLAG, "./logs" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_10 = {6, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_9};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_11 = { 10 | NIM_STRLIT_FLAG, "session.db" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_12 = {10, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_11};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bSUSYdX7Li9cqJDbeYzoJAw_13 = { 2 | NIM_STRLIT_FLAG, "en" };
static const NimStringV2 TM__bSUSYdX7Li9cqJDbeYzoJAw_14 = {2, (NimStrPayload*)&TM__bSUSYdX7Li9cqJDbeYzoJAw_13};
N_LIB_PRIVATE NimStringV2 SECRET_KEY__pkgZbasolatoZcoreZsettings_u23;
N_LIB_PRIVATE NimStringV2 LOG_DIR__pkgZbasolatoZcoreZsettings_u27;
N_LIB_PRIVATE NimStringV2 SESSION_PATH__pkgZbasolatoZcoreZsettings_u30;
N_LIB_PRIVATE tySequence__sM4lkSb7zS6F7OVMvW9cffQ COOKIE_DOMAINS__pkgZbasolatoZcoreZsettings_u35;
N_LIB_PRIVATE NimStringV2 LOCALE__pkgZbasolatoZcoreZsettings_u36;
N_LIB_PRIVATE NimStringV2 valueX60gensym3___pkgZbasolatoZcoreZsettings_u21;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
N_LIB_PRIVATE NIM_BOOL LOG_TO_CONSOLE__pkgZbasolatoZcoreZsettings_u24 = NIM_TRUE;
N_LIB_PRIVATE NIM_BOOL LOG_TO_FILE__pkgZbasolatoZcoreZsettings_u25 = NIM_FALSE;
N_LIB_PRIVATE NIM_BOOL ERROR_LOG_TO_FILE__pkgZbasolatoZcoreZsettings_u26 = NIM_FALSE;
N_LIB_PRIVATE NI SESSION_TIME__pkgZbasolatoZcoreZsettings_u28 = ((NI)120);
N_LIB_PRIVATE NIM_BOOL SESSION_EXPIRE_ON_CLOSE__pkgZbasolatoZcoreZsettings_u29 = NIM_FALSE;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(178, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/ospaths2.nim");	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atnbasolatominus0dot16dot1minus4f54fe4f58a388e25fe3d4c11176176b02418f99atsbasolatoatscoreatssettingsdotnim_Init000)(void) {
{
	NimStringV2 colontmpD_;
	NimStringV2 T2_;
	NimStringV2 T13_;
NIM_BOOL* nimErr_;
	nimfr_("settings", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/settings.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	{
		NimStringV2 colontmpD__2;
		NimStringV2 T5_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimlf_(43, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim");		colontmpD__2 = getEnv__stdZenvvars_u15(TM__bSUSYdX7Li9cqJDbeYzoJAw_3, TM__bSUSYdX7Li9cqJDbeYzoJAw_5);
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = nsuStrip(colontmpD__2, NIM_TRUE, NIM_TRUE, TM__bSUSYdX7Li9cqJDbeYzoJAw_6);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T5_); goto LA4_;}
		valueX60gensym3___pkgZbasolatoZcoreZsettings_u21 = T5_;
		nimln_(44);		{
			tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T10_;
			if (!(valueX60gensym3___pkgZbasolatoZcoreZsettings_u21.len == ((NI)0))) goto LA8_;
			T10_ = NIM_NIL;
			T10_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
			(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
			(*T10_).Sup.Sup.name = "ValueError";
			(*T10_).Sup.Sup.message = TM__bSUSYdX7Li9cqJDbeYzoJAw_8;
			(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(45);			raiseExceptionEx((Exception*)T10_, "ValueError", "settings", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/env.nim", 45);
goto LA4_;
		}
LA8_: ;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqcopy___system_u2725((&SECRET_KEY__pkgZbasolatoZcoreZsettings_u23), valueX60gensym3___pkgZbasolatoZcoreZsettings_u21);
		{
			LA4_:;
		}
		{
			nimln_(394);			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (valueX60gensym3___pkgZbasolatoZcoreZsettings_u21.p && !(valueX60gensym3___pkgZbasolatoZcoreZsettings_u21.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(valueX60gensym3___pkgZbasolatoZcoreZsettings_u21.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	nimlf_(26, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/settings.nim");	LOG_DIR__pkgZbasolatoZcoreZsettings_u27 = TM__bSUSYdX7Li9cqJDbeYzoJAw_10;
	nimln_(30);	colontmpD_ = nosgetCurrentDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T13_.len = 0; T13_.p = NIM_NIL;
	T13_ = slash___stdZprivateZospaths2_u88(colontmpD_, TM__bSUSYdX7Li9cqJDbeYzoJAw_12);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T13_); goto LA1_;}
	SESSION_PATH__pkgZbasolatoZcoreZsettings_u30 = T13_;
	nimln_(31);	COOKIE_DOMAINS__pkgZbasolatoZcoreZsettings_u35.len = 0; COOKIE_DOMAINS__pkgZbasolatoZcoreZsettings_u35.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(33);	LOCALE__pkgZbasolatoZcoreZsettings_u36 = TM__bSUSYdX7Li9cqJDbeYzoJAw_14;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

