/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@slogger.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@slogger.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ;
typedef struct tyObject_RollingFileLoggercolonObjectType___Lb3yV4QyIE9acShXuT6wbCg tyObject_RollingFileLoggercolonObjectType___Lb3yV4QyIE9acShXuT6wbCg;
typedef struct tyObject_LoggercolonObjectType___DaYkzhxQzhDzuUG4lepzDQ tyObject_LoggercolonObjectType___DaYkzhxQzhDzuUG4lepzDQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_LoggercolonObjectType___DaYkzhxQzhDzuUG4lepzDQ {
	RootObj Sup;
	tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig levelThreshold;
	NimStringV2 fmtStr;
};
struct tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ {
	tyObject_LoggercolonObjectType___DaYkzhxQzhDzuUG4lepzDQ Sup;
	NIM_BOOL useStderr;
	tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig flushThreshold;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ*, newConsoleLogger__pureZlogging_u113)(tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig levelThreshold_p0, NimStringV2 fmtStr_p1, NIM_BOOL useStderr_p2, tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig flushThreshold_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZlogging_u154)(tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__7Bn9bW3MpJ3gjungKyPI9a9cg_2 = { 11 | NIM_STRLIT_FLAG, "$levelname " };
static const NimStringV2 TM__7Bn9bW3MpJ3gjungKyPI9a9cg_3 = {11, (NimStrPayload*)&TM__7Bn9bW3MpJ3gjungKyPI9a9cg_2};
N_LIB_PRIVATE tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ* consoleLogger__pkgZbasolatoZcoreZlogger_u5;
N_LIB_PRIVATE tyObject_RollingFileLoggercolonObjectType___Lb3yV4QyIE9acShXuT6wbCg* fileLogger__pkgZbasolatoZcoreZlogger_u6;
N_LIB_PRIVATE tyObject_RollingFileLoggercolonObjectType___Lb3yV4QyIE9acShXuT6wbCg* errorFileLogger__pkgZbasolatoZcoreZlogger_u8;
N_LIB_PRIVATE NIM_BOOL fileLoggerReady__pkgZbasolatoZcoreZlogger_u7 = NIM_FALSE;
N_LIB_PRIVATE NIM_BOOL errorFileLoggerReady__pkgZbasolatoZcoreZlogger_u9 = NIM_FALSE;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atnbasolatominus0dot16dot1minus4f54fe4f58a388e25fe3d4c11176176b02418f99atsbasolatoatscoreatsloggerdotnim_Init000)(void) {
{
	tyObject_ConsoleLoggercolonObjectType___wAbaNxzuI1e9atI9bQ9cE1KdQ* T1_;
NIM_BOOL* nimErr_;
	nimfr_("logger", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/logger.nim");
nimErr_ = nimErrorFlag();
	nimlf_(7, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/logger.nim");	T1_ = NIM_NIL;
	T1_ = newConsoleLogger__pureZlogging_u113(((tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig)0), TM__7Bn9bW3MpJ3gjungKyPI9a9cg_3, NIM_FALSE, ((tyEnum_Level__7kuKkUuWYQAvhDqzCJGSig)0));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZlogging_u154(T1_); goto BeforeRet_;}
	consoleLogger__pkgZbasolatoZcoreZlogger_u5 = T1_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

