/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@sresponse.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@sresponse.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ;
typedef struct tyObject_Table__7VMwcdKPjTOBWJKprTjBww tyObject_Table__7VMwcdKPjTOBWJKprTjBww;
typedef struct tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg;
typedef struct tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ;
typedef struct RootObj RootObj;
typedef struct tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA;
typedef struct Exception Exception;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw {
	NI status;
	NimStringV2 body;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers;
};
struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ {
	tyObject_Table__7VMwcdKPjTOBWJKprTjBww* table;
	NIM_BOOL isTitleCase;
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
	tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA* next;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ {
	RootObj Sup;
	tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA callbacks;
	NIM_BOOL finished;
	Exception* error;
	NimStringV2 errorStackTrace;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ stackTrace;
	NI id;
	NimStringV2 fromProc;
};
struct tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg {
	tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ Sup;
	tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* value;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZbasolatoZcoreZresponse_u1116)(void* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZbasolatoZcoreZresponse_u423)(tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, eqdup___pureZhttpcore_u446)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZresponse_u93)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* dest_p0);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__Birm2IV5SEmEKjib2AV1sg_;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static NIM_CONST NU32 TM__AZJW7FJSQ7EpeoFy9aSEmUQ_2[3] = {3701606400, 2451933440, 719771648};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Birm2IV5SEmEKjib2AV1sg_ = {.destructor = (void*)rttiDestroy__pkgZbasolatoZcoreZresponse_u1116, .size = sizeof(tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg), .align = (NI16) NIM_ALIGNOF(tyObject_FuturecolonObjectType___Birm2IV5SEmEKjib2AV1sg), .depth = 2, .display = TM__AZJW7FJSQ7EpeoFy9aSEmUQ_2, .traceImpl = (void*)eqtrace___pkgZbasolatoZcoreZresponse_u423, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4) & (64 - 1))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZresponse_u93)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).headers);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0).headers)));
		nimRawDispose((*dest_p0).headers, ((NI)8));
	}
LA4_: ;
	if ((*dest_p0).body.p && !((*dest_p0).body.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).body.p);
}
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw*, new__pkgZbasolatoZcoreZroute_u8940)(NI status_p1, NimStringV2 body_p2, tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p3) {
	tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* result;
	NI colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* colontmpD__3;
	tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* T1_;
	nimfr_("new", "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/response.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	nimlf_(25, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/response.nim");	nimln_(24);	nimln_(25);	T1_ = NIM_NIL;
	T1_ = (tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw*) nimNewObjUninit(sizeof(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw), NIM_ALIGNOF(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw));
	colontmpD_ = status_p1;
	(*T1_).status = colontmpD_;
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD__2 = eqdup___system_u2728(body_p2);
	(*T1_).body = colontmpD__2;
	nimlf_(25, "/Users/nakagawa_shota/.nimble/pkgs2/basolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99/basolato/core/response.nim");	nimlf_(136, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	colontmpD__3 = eqdup___pureZhttpcore_u446(headers_p3);
	(*T1_).headers = colontmpD__3;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZbasolatoZcoreZresponse_u130)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw** dest_p0, tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZbasolatoZcoreZresponse_u93((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZbasolatoZcoreZresponse_u118)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZbasolatoZcoreZresponse_u121)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZbasolatoZcoreZresponse_u93((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(88, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZbasolatoZcoreZresponse_u124)(tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw** dest_p0, tyObject_ResponsecolonObjectType___XzYy0TYxg9b4hlAAfGdj4Aw* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZbasolatoZcoreZresponse_u93((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
