/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@sheader.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nbasolato-0.16.1-4f54fe4f58a388e25fe3d4c11176176b02418f99@sbasolato@score@sheader.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE NIM_THREADVAR NimStringV2 cachedDateHeaderStr__pkgZbasolatoZcoreZheader_u7;
N_LIB_PRIVATE NIM_THREADVAR NI64 cachedDateEpochSec__pkgZbasolatoZcoreZheader_u8;
