/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nhttpbeast-0.4.1-b23e57a401057dcb9b7fae1fb8279a6a2ce1d0b8@shttpbeast.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@nhttpbeast-0.4.1-b23e57a401057dcb9b7fae1fb8279a6a2ce1d0b8@shttpbeast.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE NIM_THREADVAR NimStringV2 serverDate__pkgZhttpbeast_u1763;
N_LIB_PRIVATE NU requestCounter__pkgZhttpbeast_u314 = ((NU)0);
