/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@ntiara-0.1.5-5b434fba384bb65350a8e2b23aeeeabdcefb496c@stiara@sbuilder.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@ntiara-0.1.5-5b434fba384bb65350a8e2b23aeeeabdcefb496c@stiara@sbuilder.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_2 = { 5 | NIM_STRLIT_FLAG, "&amp;" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_3 = {5, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_4 = { 4 | NIM_STRLIT_FLAG, "&lt;" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_5 = {4, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_6 = { 4 | NIM_STRLIT_FLAG, "&gt;" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_7 = {4, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_6};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_8 = { 6 | NIM_STRLIT_FLAG, "&quot;" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_9 = {6, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_8};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_10 = { 5 | NIM_STRLIT_FLAG, "&#39;" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_11 = {5, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_10};
static const struct {
  NI cap; NIM_CHAR data[158+1];
} TM__BmiaBZtMx7R0vXcGE2TbLg_12 = { 158 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__BmiaBZtMx7R0vXcGE2TbLg_13 = {158, (NimStrPayload*)&TM__BmiaBZtMx7R0vXcGE2TbLg_12};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, escapeHtml__pkgZtiaraZbuilder_u28)(NimStringV2 value_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("escapeHtml", "/Users/nakagawa_shota/.nimble/pkgs2/tiara-0.1.5-5b434fba384bb65350a8e2b23aeeeabdcefb496c/tiara/builder.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(13, "/Users/nakagawa_shota/.nimble/pkgs2/tiara-0.1.5-5b434fba384bb65350a8e2b23aeeeabdcefb496c/tiara/builder.nim");	if ((value_p0.len) < ((NI)0) || (value_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(value_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString((value_p0.len));
	{
		NIM_CHAR ch_1;
		NI i_1;
		NI L_1;
		ch_1 = (NIM_CHAR)0;
		nimlf_(267, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(268);		L_1 = value_p0.len;
		{
			nimln_(269);			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				nimlf_(14, "/Users/nakagawa_shota/.nimble/pkgs2/tiara-0.1.5-5b434fba384bb65350a8e2b23aeeeabdcefb496c/tiara/builder.nim");				if (i_1 < 0 || i_1 >= value_p0.len){ raiseIndexError2(i_1,value_p0.len-1); goto BeforeRet_;
				}
				ch_1 = value_p0.p->data[i_1];
				nimln_(15);				switch (((NU8)(ch_1))) {
				case 38:
				{
					nimln_(17);					prepareAdd((&result), 5);
appendString((&result), TM__BmiaBZtMx7R0vXcGE2TbLg_3);
				}
				break;
				case 60:
				{
					nimln_(19);					prepareAdd((&result), 4);
appendString((&result), TM__BmiaBZtMx7R0vXcGE2TbLg_5);
				}
				break;
				case 62:
				{
					nimln_(21);					prepareAdd((&result), 4);
appendString((&result), TM__BmiaBZtMx7R0vXcGE2TbLg_7);
				}
				break;
				case 34:
				{
					nimln_(23);					prepareAdd((&result), 6);
appendString((&result), TM__BmiaBZtMx7R0vXcGE2TbLg_9);
				}
				break;
				case 39:
				{
					nimln_(25);					prepareAdd((&result), 5);
appendString((&result), TM__BmiaBZtMx7R0vXcGE2TbLg_11);
				}
				break;
				default:
				{
					nimln_(27);					nimAddCharV1((&result), ch_1);
				}
				break;
				}
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(272);				{
					if (!!((value_p0.len == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u95(TM__BmiaBZtMx7R0vXcGE2TbLg_13);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
