/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pasyncnet.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pasyncnet.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_AsyncSocketDesc__uovOBxHWD50yTVzyZIF6fg tyObject_AsyncSocketDesc__uovOBxHWD50yTVzyZIF6fg;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZasyncnet_u39)(tyObject_AsyncSocketDesc__uovOBxHWD50yTVzyZIF6fg* dest_p0) {
}
