/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@phttpcore.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@phttpcore.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_Table__7VMwcdKPjTOBWJKprTjBww tyObject_Table__7VMwcdKPjTOBWJKprTjBww;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA;
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ {
	tyObject_Table__7VMwcdKPjTOBWJKprTjBww* table;
	NIM_BOOL isTitleCase;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u302)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u585)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1);
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___pureZhttpcore_u960)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, eqdup___system_u5641)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__7VMwcdKPjTOBWJKprTjBww*, newTable__pureZhttpcore_u133)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u1255)(tyObject_Table__7VMwcdKPjTOBWJKprTjBww* t_p0, NimStringV2 key_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_2 = { 4 | NIM_STRLIT_FLAG, "HEAD" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_3 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_4 = { 3 | NIM_STRLIT_FLAG, "GET" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_5 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_6 = { 4 | NIM_STRLIT_FLAG, "POST" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_7 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_6};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_8 = { 3 | NIM_STRLIT_FLAG, "PUT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_9 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Evu9b2R1utZubyCikahWx1g_10 = { 6 | NIM_STRLIT_FLAG, "DELETE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_11 = {6, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_10};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_12 = { 5 | NIM_STRLIT_FLAG, "TRACE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_13 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_12};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_14 = { 7 | NIM_STRLIT_FLAG, "OPTIONS" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_15 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_14};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_16 = { 7 | NIM_STRLIT_FLAG, "CONNECT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_17 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_16};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_18 = { 5 | NIM_STRLIT_FLAG, "PATCH" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_19 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_18};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Evu9b2R1utZubyCikahWx1g_20 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_21 = {0, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_20};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZhttpcore_u34)(tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)0):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_3;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)1):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_5;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)2):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_7;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)3):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_9;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)4):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_11;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)5):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_13;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)6):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_15;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)7):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_17;
	}
	break;
	case ((tyEnum_HttpMethod__9bNK9aI6AnwblUzPkeUOhq9bA)8):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_19;
	}
	break;
	default:
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_21;
	}
	break;
	}
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4) & (64 - 1))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).table);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u302((*dest_p0).table);
		nimRawDispose((*dest_p0).table, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u3103)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].p && !(dest_p0.p->data[colontmp_].p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NimStringV2));
}
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0) {
	NimStringV2 result;
	NIM_BOOL upper_1;
NIM_BOOL* nimErr_;
	nimfr_("toTitleCase", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(123, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(124);	upper_1 = NIM_TRUE;
	{
		NI i_1;
		NI colontmp_;
		NI TM__Evu9b2R1utZubyCikahWx1g_22;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(125, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_22)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Evu9b2R1utZubyCikahWx1g_22);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR colontmpD_;
				NIM_CHAR colontmpD__2;
				NI TM__Evu9b2R1utZubyCikahWx1g_23;
				if (!(res_1 <= colontmp_)) goto LA3;
				colontmpD_ = (NIM_CHAR)0;
				colontmpD__2 = (NIM_CHAR)0;
				nimlf_(125, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");				i_1 = ((NI) (res_1));
				nimln_(126);				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				{
					if (!upper_1) goto LA6_;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					colontmpD_ = nsuToUpperAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = colontmpD_;
				}
				goto LA4_;
LA6_: ;
				{
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					colontmpD__2 = nsuToLowerAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = colontmpD__2;
				}
LA4_: ;
				nimln_(127);				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				upper_1 = ((NU8)(s_p0.p->data[i_1]) == (NU8)(45));
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_23)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__Evu9b2R1utZubyCikahWx1g_23);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 s_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("toCaseInsensitive", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(*headers_p0).isTitleCase) goto LA4_;
		nimln_(129);		nimln_(131);		result = toTitleCase__pureZhttpcore_u101(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		nimln_(129);		nimln_(131);		result = nsuToLowerAsciiStr(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u4009)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(220);	nimln_(219);	nimln_(220);	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = hasKey__pureZhttpcore_u585((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toString__pureZhttpcore_u3139)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ values_p0) {
	NimStringV2 result;
	nimfr_("toString", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(171, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (((NI)0) < 0 || ((NI)0) >= values_p0.len){ raiseIndexError2(((NI)0),values_p0.len-1); goto BeforeRet_;
	}
	eqcopy___system_u2725((&result), values_p0.p->data[((NI)0)]);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZhttpcore_u3022)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ tmp_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T2_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	tmp_1.len = 0; tmp_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(167, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T2_ = X5BX5D___pureZhttpcore_u960((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	tmp_1 = (*T2_);
	nimln_(168);	nimln_(158);	nimln_(168);	nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD__2 = eqdup___system_u5641(tmp_1);
	result = colontmpD__2;
	nimln_(394);	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, newHttpHeaders__pureZhttpcore_u114)(NIM_BOOL titleCase_p0) {
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* result;
	NIM_BOOL colontmpD_;
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newHttpHeaders", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = (NIM_BOOL)0;
	nimlf_(136, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*) nimNewObjUninit(sizeof(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ), NIM_ALIGNOF(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ));
	(*T1_).table = newTable__pureZhttpcore_u133(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_ = titleCase_p0;
	(*T1_).isTitleCase = colontmpD_;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u3201)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* headers_p0, NimStringV2 key_p1, NimStringV2 value_p2) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(183);	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 1; T1_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD__2 = eqdup___system_u2728(value_p2);
	T1_.p->data[0] = colontmpD__2;
	nimlf_(183, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/httpcore.nim");	X5BX5Deq___pureZhttpcore_u1255((*headers_p0).table, colontmpD_, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(88, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ*, eqdup___pureZhttpcore_u446)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* src_p0) {
	tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u440)(tyObject_HttpHeaderscolonObjectType___GEmYP0OyTocqWxGjm6f9aNQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
