/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstreams.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstreams.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA;
typedef struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__Xl32m0kTaH9ahJZb5rqVy6w) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ooJWa8lnlfnobNqxEOtnNA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__E19bfDo0XX9btMFiY2C0tGGg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qvufjYFbEQ9cqXk4e8pAzJQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__wBfXfmCdEwRLtDI7TCPoAQ) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__ohJ27oJZLprJ3hzTGNCkpA) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__qcX1k0ZWyDvPcQjruoqTPg) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__E6HHS1dkEvJbg7JG3Yyt9ag) (tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg {
	RootObj Sup;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w closeImpl;
	tyProc__ooJWa8lnlfnobNqxEOtnNA atEndImpl;
	tyProc__E19bfDo0XX9btMFiY2C0tGGg setPositionImpl;
	tyProc__qvufjYFbEQ9cqXk4e8pAzJQ getPositionImpl;
	tyProc__wBfXfmCdEwRLtDI7TCPoAQ readDataStrImpl;
	tyProc__ohJ27oJZLprJ3hzTGNCkpA readLineImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg readDataImpl;
	tyProc__qcX1k0ZWyDvPcQjruoqTPg peekDataImpl;
	tyProc__E6HHS1dkEvJbg7JG3Yyt9ag writeDataImpl;
	tyProc__Xl32m0kTaH9ahJZb5rqVy6w flushImpl;
};
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
typedef NU8 tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA;
struct tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA {
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg Sup;
	FILE* f;
};
typedef NU8 tyEnum_FileSeekPos__7dkAONRaW9a9cMnBdtB9am1pQ;
struct tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA {
	NI a;
	NI b;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u221)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u212)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u413)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*, newFileStream__pureZstreams_u1185)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u1093)(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, fsClose__pureZstreams_u1084)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u269)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd__pureZstreams_u1151)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u369)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, fsSetPosition__pureZstreams_u1154)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, setFilePos__stdZsyncio_u503)(FILE* f_p0, NI64 pos_p1, tyEnum_FileSeekPos__7dkAONRaW9a9cMnBdtB9am1pQ relativeTo_p2);
N_LIB_PRIVATE N_NIMCALL(NI, fsGetPosition__pureZstreams_u1157)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, getFilePos__stdZsyncio_u526)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NI, fsReadDataStr__pureZstreams_u1165)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, fsReadData__pureZstreams_u1160)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsReadLine__pureZstreams_u1181)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u291)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NI, fsPeekData__pureZstreams_u1171)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, fsWriteData__pureZstreams_u1177)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew*, newEIO__pureZstreams_u2)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9229)(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, fsFlush__pureZstreams_u1149)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u278)(FILE* f_p0);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(void, prepareMutation__system_u2486)(NimStringV2* s_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_2 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_3 = {1, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_2};
N_LIB_PRIVATE TNimTypeV2 NTIv2__2f9ao0KVyvI6avM0ODeLAZA_;
extern TNimTypeV2 NTIv2__OefSIx6jC6YPnq9aG8TlFew_;
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_7 = { 22 | NIM_STRLIT_FLAG, "cannot write to stream" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_8 = {22, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_7};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static NIM_CONST NU32 TM__Ue7tnBcsL67VCiRfvt8q0A_4[3] = {3701606400, 2812622592, 4285059072};
N_LIB_PRIVATE TNimTypeV2 NTIv2__2f9ao0KVyvI6avM0ODeLAZA_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA), .align = (NI16) NIM_ALIGNOF(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA), .depth = 2, .display = TM__Ue7tnBcsL67VCiRfvt8q0A_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u212)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
NIM_BOOL* nimErr_;
	nimfr_("writeData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(348, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	(*s_p0).writeDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u221)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2 x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(381);	{
		if (!(((NI)0) < x_p1.len)) goto LA3_;
		nimln_(386);		writeData__pureZstreams_u212(s_p0, ((void*) (nimToCStringConv(x_p1))), x_p1.len);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, writeLine__pureZstreams_u231)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* args_p1, NI args_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("writeLine", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* str_1;
		NI i_1;
		str_1 = (NimStringV2*)0;
		nimlf_(18, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_1 < args_p1Len_0)) goto LA3;
				nimlf_(411, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");				if (i_1 < 0 || i_1 >= args_p1Len_0){ raiseIndexError2(i_1,args_p1Len_0-1); goto BeforeRet_;
				}
				str_1 = (&args_p1[i_1]);
				write__pureZstreams_u221(s_p0, (*str_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(412, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	write__pureZstreams_u221(s_p0, TM__Ue7tnBcsL67VCiRfvt8q0A_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(518, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u1093)(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(268, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsClose__pureZstreams_u1084)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("fsClose", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1336, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	{
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		if (!!(((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f == ((FILE*) NIM_NIL)))) goto LA3_;
		nimln_(1337);		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		close__stdZsyncio_u269((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(1338);		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		(*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f = ((FILE*) NIM_NIL);
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd__pureZstreams_u1151)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("fsAtEnd", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	result = endOfFile__stdZsyncio_u369((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsSetPosition__pureZstreams_u1154)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NI pos_p1) {
NIM_BOOL* nimErr_;
	nimfr_("fsSetPosition", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	setFilePos__stdZsyncio_u503((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, ((NI64) (pos_p1)), ((tyEnum_FileSeekPos__7dkAONRaW9a9cMnBdtB9am1pQ)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, fsGetPosition__pureZstreams_u1157)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0) {
	NI result;
	NI64 T1_;
NIM_BOOL* nimErr_;
	nimfr_("fsGetPosition", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	T1_ = (NI64)0;
	T1_ = getFilePos__stdZsyncio_u526((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsReadDataStr__pureZstreams_u1165)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2) {
	NI result;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_5;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_6;
NIM_BOOL* nimErr_;
	nimfr_("fsReadDataStr", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1348);	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	if (slice_p2.a < 0 || slice_p2.a >= (*buffer_p1).len){ raiseIndexError2(slice_p2.a,(*buffer_p1).len-1); goto BeforeRet_;
	}
	if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_5), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_6)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_6)) < ((NI)0) || ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_6)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_6), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = readBuffer__stdZsyncio_u165((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, ((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_6)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsReadData__pureZstreams_u1160)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("fsReadData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1345);	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = readBuffer__stdZsyncio_u165((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, buffer_p1, (bufLen_p2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsReadLine__pureZstreams_u1181)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* line_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("fsReadLine", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(1360);	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	result = readLine__stdZsyncio_u291((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, line_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsPeekData__pureZstreams_u1171)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	NI pos_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("fsPeekData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1351);	pos_1 = fsGetPosition__pureZstreams_u1157(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1353);	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto LA1_;
	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	result = readBuffer__stdZsyncio_u165((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, buffer_p1, (bufLen_p2));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(1352);		fsSetPosition__pureZstreams_u1154(s_p0, pos_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew*, newEIO__pureZstreams_u2)(NimStringV2 msg_p0) {
	tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* result;
	nimfr_("newEIO", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
	result = NIM_NIL;
	nimlf_(3031, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqdestroy___system_u9229(result);
	nimlf_(109, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	result = (tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew*) nimNewObj(sizeof(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew), NIM_ALIGNOF(tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew));
	(*result).Sup.Sup.Sup.m_type = (&NTIv2__OefSIx6jC6YPnq9aG8TlFew_);
	(*result).Sup.Sup.name = "IOError";
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqcopy___system_u2725((&(*result).Sup.Sup.message), msg_p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsWriteData__pureZstreams_u1177)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
NIM_BOOL* nimErr_;
	nimfr_("fsWriteData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1356, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	{
		NI T3_;
		tyObject_IOError__OefSIx6jC6YPnq9aG8TlFew* T6_;
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = writeBuffer__stdZsyncio_u196((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f, buffer_p1, (bufLen_p2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((T3_ == bufLen_p2))) goto LA4_;
		nimln_(1357);		T6_ = NIM_NIL;
		T6_ = newEIO__pureZstreams_u2(TM__Ue7tnBcsL67VCiRfvt8q0A_8);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u9229(T6_); goto BeforeRet_;}
		raiseExceptionEx((Exception*)T6_, "IOError", "fsWriteData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim", 1357);
goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, fsFlush__pureZstreams_u1149)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("fsFlush", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 4285059072)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	flushFile__stdZsyncio_u278((*((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*, newFileStream__pureZstreams_u1185)(FILE* f_p0) {
	tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* result;
	nimfr_("newFileStream", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
	result = NIM_NIL;
	nimln_(1336);	eqdestroy___pureZstreams_u1093(result);
	nimln_(1392);	result = (tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) nimNewObj(sizeof(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA), NIM_ALIGNOF(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA));
	(*result).Sup.Sup.m_type = (&NTIv2__2f9ao0KVyvI6avM0ODeLAZA_);
	nimln_(1393);	(*result).f = f_p0;
	nimln_(1394);	(*result).Sup.closeImpl = fsClose__pureZstreams_u1084;
	nimln_(1395);	(*result).Sup.atEndImpl = fsAtEnd__pureZstreams_u1151;
	nimln_(1396);	(*result).Sup.setPositionImpl = fsSetPosition__pureZstreams_u1154;
	nimln_(1397);	(*result).Sup.getPositionImpl = fsGetPosition__pureZstreams_u1157;
	nimln_(1398);	(*result).Sup.readDataStrImpl = fsReadDataStr__pureZstreams_u1165;
	nimln_(1399);	(*result).Sup.readDataImpl = fsReadData__pureZstreams_u1160;
	nimln_(1400);	(*result).Sup.readLineImpl = fsReadLine__pureZstreams_u1181;
	nimln_(1401);	(*result).Sup.peekDataImpl = fsPeekData__pureZstreams_u1171;
	nimln_(1402);	(*result).Sup.writeDataImpl = fsWriteData__pureZstreams_u1177;
	nimln_(1403);	(*result).Sup.flushImpl = fsFlush__pureZstreams_u1149;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*, newFileStream__pureZstreams_u1210)(NimStringV2 filename_p0, tyEnum_FileMode__6JKXoak9aGtpltnS9apnuBNA mode_p1, NI bufSize_p2) {
	tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA* result;
	FILE* f_1;
NIM_BOOL* nimErr_;
	nimfr_("newFileStream", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(1440);	f_1 = 0;
	nimln_(1441);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u413(&f_1, filename_p0, mode_p1, bufSize_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = newFileStream__pureZstreams_u1185(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(1442);		result = ((tyObject_FileStreamObj__2f9ao0KVyvI6avM0ODeLAZA*) NIM_NIL);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(47, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T1_));
	nimlf_(48, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_u789)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg** dest_p0, tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, prepareMutation__system_u2486)(NimStringV2* s_p0) {
	NimStringV2* s_2;
	s_2 = s_p0;
	nimPrepareStrMutationV2(((NimStringV2*) (s_2)));
}
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("readData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(247, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");	result = (*s_p0).readDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_u84)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__A0KkkpcDPkJooHq9bpmkAsA slice_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("readDataStr", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(258);	{
		if (!!(((*s_p0).readDataStrImpl == NIM_NIL))) goto LA3_;
		nimln_(259);		result = (*s_p0).readDataStrImpl(s_p0, buffer_p1, slice_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_9;
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_10;
		nimln_(264);		prepareMutation__system_u2486(buffer_p1);
		nimln_(265);		if (slice_p2.a < 0 || slice_p2.a >= (*buffer_p1).len){ raiseIndexError2(slice_p2.a,(*buffer_p1).len-1); goto BeforeRet_;
		}
		if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_9)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_9), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_10)) { raiseOverflow(); goto BeforeRet_;
		};
		result = readData__pureZstreams_u78(s_p0, ((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_10));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("close", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/streams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(194);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s_p0 == 0));
		if (!(T3_)) goto LA4_;
		T3_ = !(((*s_p0).closeImpl == 0));
LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(195);		(*s_p0).closeImpl(s_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
}
