/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstd@sexitprocs.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstd@sexitprocs.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__ZbFPgQacMbcNAB9brdE8MLA tySequence__ZbFPgQacMbcNAB9brdE8MLA;
typedef struct tySequence__ZbFPgQacMbcNAB9brdE8MLA_Content tySequence__ZbFPgQacMbcNAB9brdE8MLA_Content;
typedef struct tyObject_Fun__l9bnc9azp19br7KBjokJDMK9ag tyObject_Fun__l9bnc9azp19br7KBjokJDMK9ag;
struct tySequence__ZbFPgQacMbcNAB9brdE8MLA {
  NI len; tySequence__ZbFPgQacMbcNAB9brdE8MLA_Content* p;
};
typedef NU8 tyEnum_FunKind__jLBJ1uXQlSvNVeXj9bc6eDw;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_NOCONV_PTR(void, tyProc__vhjNbzH0Mvv2fTvoe1717Q) (void);
struct tyObject_Fun__l9bnc9azp19br7KBjokJDMK9ag {
	tyEnum_FunKind__jLBJ1uXQlSvNVeXj9bc6eDw kind;
union{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA fun1;
	tyProc__vhjNbzH0Mvv2fTvoe1717Q fun2;
};
};
struct tySequence__ZbFPgQacMbcNAB9brdE8MLA_Content { NI cap; tyObject_Fun__l9bnc9azp19br7KBjokJDMK9ag data[SEQ_DECL_SIZE]; };
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE tySequence__ZbFPgQacMbcNAB9brdE8MLA gFuns__stdZexitprocs_u15;
N_LIB_PRIVATE pthread_mutex_t gFunsLock__stdZexitprocs_u14;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NI nim_program_result;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0) {
	pthread_mutex_init(lock_p0, ((pthread_mutexattr_t*) NIM_NIL));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setProgramResult__stdZexitprocs_u241)(NI a_p0) {
	nimfr_("setProgramResult", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/exitprocs.nim");
	nimlf_(87, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/exitprocs.nim");	nim_program_result = a_p0;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("exitprocs", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/exitprocs.nim");
nimErr_ = nimErrorFlag();
	nimln_(27);	initLock__coreZlocks_u7((&gFunsLock__stdZexitprocs_u14));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

