/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstrutils.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@pstrutils.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
typedef NU8 tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg;
typedef NIM_CHAR tyArray__Dz6OE1kpzz8bnx9batFy1Cw[6];
typedef NIM_CHAR tyArray__WALV5e0ysjOIjCclEgOBNg[2501];
typedef NIM_CHAR tyArray__TT9acfuNJCVQl0Hx4BpdjEA[3];
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2661)(NimStringV2 formatstr_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0);
static N_INLINE(NF, abs__system_u5241)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2648)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9118)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2731)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__pureZstrutils_u123)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u256)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2722)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1634)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
extern TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = { 23 | NIM_STRLIT_FLAG, "invalid format string: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 = {23, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_7};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_52 = { 8 | NIM_STRLIT_FLAG, "Printall" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_53 = {8, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_52};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_54 = { 13 | NIM_STRLIT_FLAG, "Printfailures" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_55 = {13, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_54};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_56 = { 9 | NIM_STRLIT_FLAG, "Printnone" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_57 = {9, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_56};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_58 = { 20 | NIM_STRLIT_FLAG, "Invalid enum value: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_59 = {20, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_58};
static const struct {
  NI cap; NIM_CHAR data[113+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_77 = { 113 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim(406, 9) `not (\'\\x00\' in Whitespace)` " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_78 = {113, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_77};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_89 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_90 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_89};
N_LIB_PRIVATE NIM_CONST tyArray__TT9acfuNJCVQl0Hx4BpdjEA floatFormatToChar__pureZstrutils_u2259 = {103,
102,
101}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
	nimfr_("repeat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	nimlf_(1351, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result = mnewString(count_p1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(1352, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1352, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = c_p0;
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2661)(NimStringV2 formatstr_p0) {
	tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T1_;
	NimStringV2 T2_;
	nimfr_("invalidFormatString", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
	(*T1_).Sup.Sup.name = "ValueError";
	nimlf_(2831, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(formatstr_p0.len + 23);
appendString((&T2_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_8);
appendString((&T2_), formatstr_p0);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim", 2831);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	nimlf_(1302, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__system_u5241)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__system_u1705(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1705(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__system_u1705(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u5241(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u5241(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");
{	result = (NIM_CHAR)0;
	nimlf_(2, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(3);		if (nimAddInt(((NU8)(c_p0)), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(5);		result = c_p0;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym24__1;
	NI bLenX60gensym24__1;
	NI iX60gensym24__1;
	NI jX60gensym24__1;
NIM_BOOL* nimErr_;
	nimfr_("cmpIgnoreStyle", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym24__1 = a_p0.len;
	bLenX60gensym24__1 = b_p1.len;
	iX60gensym24__1 = ((NI)0);
	jX60gensym24__1 = ((NI)0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym24__1;
			NIM_CHAR bbX60gensym24__1;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24__1 < aLenX60gensym24__1);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0.p->data[iX60gensym24__1]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24__1 += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24__1 < bLenX60gensym24__1);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1.p->data[jX60gensym24__1]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24__1 += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24__1 < aLenX60gensym24__1)) goto LA13_;
				colontmpD_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0.p->data[iX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym24__1 = colontmpD_;
			}
			goto LA11_;
LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym24__1 = colontmpD__2;
			}
LA11_: ;
			{
				if (!(jX60gensym24__1 < bLenX60gensym24__1)) goto LA18_;
				colontmpD__3 = toLowerAscii__stdZprivateZstrimpl_u1(b_p1.p->data[jX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym24__1 = colontmpD__3;
			}
			goto LA16_;
LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym24__1 = colontmpD__4;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24__1)) - ((NU8)(bbX60gensym24__1)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24__1 <= iX60gensym24__1)) goto LA27_;
				{
					if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24__1 += ((NI)1);
			jX60gensym24__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2648)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("findNormalized", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(2823, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	i_1 = ((NI)0);
	{
		nimln_(2824);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
			if (!(i_1 < (inArray_p1Len_0-1))) goto LA2;
			nimln_(2825);			{
				NI T5_;
				if (i_1 < 0 || i_1 >= inArray_p1Len_0){ raiseIndexError2(i_1,inArray_p1Len_0-1); goto BeforeRet_;
				}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI)0))) goto LA6_;
				nimln_(2822);				nimln_(2825);				result = i_1;
				goto BeforeRet_;
			}
LA6_: ;
			nimln_(2826);			if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
		} LA2: ;
	}
	nimln_(2828);	nimln_(2822);	nimln_(2828);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0) {
	NI i_1;
	NI num_1;
NIM_BOOL* nimErr_;
	nimfr_("addf", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2837);	i_1 = ((NI)0);
	nimln_(2838);	num_1 = ((NI)0);
	{
		nimln_(2839);		while (1) {
			if (!(i_1 < formatstr_p1.len)) goto LA2;
			nimln_(2840);			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
				T5_ = (NIM_BOOL)0;
				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				T5_ = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
				};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5) < formatstr_p1.len);
LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(2841);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6) >= formatstr_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6),formatstr_p1.len-1); goto BeforeRet_;
				}
				switch (((NU8)(formatstr_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
					nimln_(2843);					{
						if (!((a_p2Len_0-1) < num_1)) goto LA12_;
						invalidFormatString__pureZstrutils_u2661(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA12_: ;
					nimln_(2844);					if (num_1 < 0 || num_1 >= a_p2Len_0){ raiseIndexError2(num_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[num_1].len + 0);
appendString((&(*s_p0)), a_p2[num_1]);
					nimln_(2845);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
					nimln_(2846);					if (nimAddInt(num_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
					};
					num_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
					nimln_(2848);					nimAddCharV1((&(*s_p0)), 36);
					nimln_(2849);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
					NIM_BOOL negative_1;
					NI idx_1;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					nimln_(2851);					j_1 = ((NI)0);
					nimln_(2852);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
					nimln_(2853);					if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_1 = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(45));
					nimln_(2854);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
						if (!negative_1) goto LA18_;
						if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
					}
LA18_: ;
					{
						nimln_(2855);						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
							T22_ = (NIM_BOOL)0;
							T22_ = (i_1 < formatstr_p1.len);
							if (!(T22_)) goto LA23_;
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							T22_ = (((NU8)(formatstr_p1.p->data[i_1])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[i_1])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							nimln_(2856);							if (nimMulInt(j_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto BeforeRet_;
							};
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14), ((NU8)(formatstr_p1.p->data[i_1])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto BeforeRet_;
							};
							j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
							nimln_(2857);							if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto BeforeRet_;
							};
							i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
						} LA21: ;
					}
					nimln_(2858);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
						if (!!(negative_1)) goto LA26_;
						if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
						idx_1 = colontmpD_;
					}
					goto LA24_;
LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
						if (nimSubInt(a_p2Len_0, j_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
						idx_1 = colontmpD__2;
					}
LA24_: ;
					nimln_(2859);					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx_1 < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx_1);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_u2661(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA33_: ;
					nimln_(2860);					if (idx_1 < 0 || idx_1 >= a_p2Len_0){ raiseIndexError2(idx_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[idx_1].len + 0);
appendString((&(*s_p0)), a_p2[idx_1]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
					NI k_1;
					NIM_BOOL negative_2;
					NI isNumber_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
					nimln_(2862);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); goto BeforeRet_;
					};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20);
					nimln_(2863);					k_1 = ((NI)0);
					nimln_(2864);					if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_2 = ((NU8)(formatstr_p1.p->data[j_2]) == (NU8)(45));
					nimln_(2865);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); goto BeforeRet_;
						};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21);
					}
LA38_: ;
					nimln_(2866);					isNumber_1 = ((NI)0);
					{
						nimln_(2867);						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr_p1.len);
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
							}
							T42_ = !((((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							nimln_(2868);							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (!(((NU8)(formatstr_p1.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								nimln_(2869);								if (nimMulInt(k_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); goto BeforeRet_;
								};
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22), ((NU8)(formatstr_p1.p->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); goto BeforeRet_;
								};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); goto BeforeRet_;
								};
								k_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
								nimln_(2870);								{
									if (!(isNumber_1 == ((NI)0))) goto LA50_;
									isNumber_1 = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								nimln_(2872);								isNumber_1 = ((NI)-1);
							}
LA44_: ;
							nimln_(2873);							if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); goto BeforeRet_;
							};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25);
						} LA41: ;
					}
					nimln_(2874);					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber_1 == ((NI)1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						nimln_(2875);						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
							idx_2 = colontmpD__3;
						}
						goto LA57_;
LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
							if (nimSubInt(a_p2Len_0, k_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__4 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27);
							idx_2 = colontmpD__4;
						}
LA57_: ;
						nimln_(2876);						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_u2661(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA66_: ;
						nimln_(2877);						if (idx_2 < 0 || idx_2 >= a_p2Len_0){ raiseIndexError2(idx_2,a_p2Len_0-1); goto BeforeRet_;
						}
						prepareAdd((&(*s_p0)), a_p2[idx_2].len + 0);
appendString((&(*s_p0)), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x_1;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						nimln_(2879);						if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); goto LA69_;
						};
						if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); goto LA69_;
						};
						colontmpD__5 = substr__system_u9118(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31));
						x_1 = findNormalized__pureZstrutils_u2648(colontmpD__5, a_p2, a_p2Len_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						nimln_(2880);						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x_1);
							if (!(T72_)) goto LA73_;
							T72_ = (x_1 < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); goto LA69_;
							};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32),a_p2Len_0-1); goto LA69_;
							}
							prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)]);
						}
						goto LA70_;
LA74_: ;
						{
							nimln_(2881);							invalidFormatString__pureZstrutils_u2661(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
LA70_: ;
						{
							LA69_:;
						}
						{
							nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA53_: ;
					nimlf_(2882, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_37;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimln_(2884);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); goto LA80_;
					};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34);
					{
						nimln_(2885);						while (1) {
							NIM_BOOL T83_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr_p1.len);
							if (!(T83_)) goto LA84_;
							if (j_3 < 0 || j_3 >= formatstr_p1.len){ raiseIndexError2(j_3,formatstr_p1.len-1); goto LA80_;
							}
							T83_ = (((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1.p->data[j_3])) == ((NU8)(95)));
LA84_: ;
							if (!T83_) goto LA82;
							if (nimAddInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); goto LA80_;
							};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
						} LA82: ;
					}
					nimln_(2886);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); goto LA80_;
					};
					if (nimSubInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) { raiseOverflow(); goto LA80_;
					};
					colontmpD__6 = substr__system_u9118(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37));
					x_2 = findNormalized__pureZstrutils_u2648(colontmpD__6, a_p2, a_p2Len_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					nimln_(2887);					{
						NIM_BOOL T87_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_38;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI)0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (a_p2Len_0-1));
LA88_: ;
						if (!T87_) goto LA89_;
						if (nimAddInt(x_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)) { raiseOverflow(); goto LA80_;
						};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38),a_p2Len_0-1); goto LA80_;
						}
						prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)]);
					}
					goto LA85_;
LA89_: ;
					{
						nimln_(2888);						invalidFormatString__pureZstrutils_u2661(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
LA85_: ;
					nimln_(2889);					i_1 = j_3;
					{
						LA80_:;
					}
					{
						nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					nimlf_(2891, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					invalidFormatString__pureZstrutils_u2661(formatstr_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
				nimln_(2893);				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				nimAddCharV1((&(*s_p0)), formatstr_p1.p->data[i_1]);
				nimln_(2894);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
			}
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatSingleElem)(NimStringV2 formatstr_p0, NimStringV2 a_p1) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
	tyArray__YgExxhfgKcesA5EOUj1MOA T1_;
NIM_BOOL* nimErr_;
	nimfr_("%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2953);	if (nimAddInt(formatstr_p0.len, a_p1.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)));
	nimln_(2954);	T1_[0] = a_p1;
	nsuAddf((&result), formatstr_p0, T1_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
	tyArray__Dz6OE1kpzz8bnx9batFy1Cw frmtstr_1;
	tyArray__WALV5e0ysjOIjCclEgOBNg buf_1;
	int L_1;
	nimfr_("formatBiggestFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	L_1 = (int)0;
	nimln_(2554);	frmtstr_1[(((NI)0))- 0] = 37;
	nimln_(2555);	{
		if (!(((NI)0) <= precision_p2)) goto LA3_;
		nimln_(2556);		frmtstr_1[(((NI)1))- 0] = 35;
		nimln_(2557);		frmtstr_1[(((NI)2))- 0] = 46;
		nimln_(2558);		frmtstr_1[(((NI)3))- 0] = 42;
		nimln_(2559);		frmtstr_1[(((NI)4))- 0] = floatFormatToChar__pureZstrutils_u2259[(format_p1)- 0];
		nimln_(2560);		frmtstr_1[(((NI)5))- 0] = 0;
		nimln_(2561);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), precision_p2, f_p0);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(2563);		frmtstr_1[(((NI)1))- 0] = floatFormatToChar__pureZstrutils_u2259[(format_p1)- 0];
		nimln_(2564);		frmtstr_1[(((NI)2))- 0] = 0;
		nimln_(2565);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), f_p0);
	}
LA1_: ;
	nimln_(2566);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI) (L_1)));
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
				if (!(res_1 < L_1)) goto LA8;
				nimlf_(2567, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				i_1 = res_1;
				nimln_(2570);				{
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					if (!(((NU8)(buf_1[(i_1)- 0])) == ((NU8)(46)) || ((NU8)(buf_1[(i_1)- 0])) == ((NU8)(44)))) goto LA11_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = decimalSep_p3;
				}
				goto LA9_;
LA11_: ;
				{
					nimln_(2571);					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					result.p->data[i_1] = buf_1[(i_1)- 0];
				}
LA9_: ;
				nimlf_(140, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_40 < (-2147483647 -1) || TM__JGc9b9bh2D3nTdUR7TGyq8aA_40 > 2147483647){ raiseOverflow(); goto BeforeRet_;
				}
				res_1 = (NI32)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatFloat)(NF f_p0, tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("formatFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(2601, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result = nsuformatBiggestFloat(f_p0, format_p1, precision_p2, decimalSep_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
NIM_BOOL* nimErr_;
	nimfr_("%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2946);	if (nimAddInt(formatstr_p0.len, (NI)((NU64)(a_p1Len_0) << (NU64)(((NI)4) & (64 - 1))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)));
	nimln_(2947);	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3) {
	NimStringV2 result;
	NI first_1;
	NI last_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
	nimfr_("strip", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(2996);	first_1 = ((NI)0);
	nimln_(2997);	if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); goto BeforeRet_;
	};
	last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42);
	nimln_(2998);	{
		if (!leading_p1) goto LA3_;
		{
			nimln_(2999);			while (1) {
				NIM_BOOL T7_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
				T7_ = (NIM_BOOL)0;
				T7_ = (first_1 <= last_1);
				if (!(T7_)) goto LA8_;
				if (first_1 < 0 || first_1 >= s_p0.len){ raiseIndexError2(first_1,s_p0.len-1); goto BeforeRet_;
				}
				T7_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[first_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[first_1]))))&7U)))!=0);
LA8_: ;
				if (!T7_) goto LA6;
				if (nimAddInt(first_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); goto BeforeRet_;
				};
				first_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43);
			} LA6: ;
		}
	}
LA3_: ;
	nimln_(3000);	{
		if (!trailing_p2) goto LA11_;
		{
			nimln_(3001);			while (1) {
				NIM_BOOL T15_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
				T15_ = (NIM_BOOL)0;
				T15_ = (first_1 <= last_1);
				if (!(T15_)) goto LA16_;
				if (last_1 < 0 || last_1 >= s_p0.len){ raiseIndexError2(last_1,s_p0.len-1); goto BeforeRet_;
				}
				T15_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[last_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[last_1]))))&7U)))!=0);
LA16_: ;
				if (!T15_) goto LA14;
				if (nimSubInt(last_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44);
			} LA14: ;
		}
	}
LA11_: ;
	nimln_(3002);	result = substr__system_u9118(s_p0, first_1, last_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
	nimln_(218);	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(219);		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(221);		result = c_p0;
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuIntToStr)(NI x_p0, NI minchars_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("intToStr", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(1145);	if (x_p0 == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
	}
	result = dollar___systemZdollars_u14((x_p0 > 0? (x_p0) : -(x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(1146, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if (nimSubInt(minchars_p1, result.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_45);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NimStringV2 T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_46;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1146, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				nimlf_(1147, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = rawNewString(result.len + 1);
appendChar((&T4_), 48);
appendString((&T4_), result);
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___system_u2731((&result), T4_);
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46);
			} LA3: ;
		}
	}
	nimlf_(1148, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	{
		NimStringV2 T9_;
		if (!(x_p0 < ((NI)0))) goto LA7_;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		nimlf_(1149, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = rawNewString(result.len + 1);
appendChar((&T9_), 45);
appendString((&T9_), result);
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqsink___system_u2731((&result), T9_);
	}
LA7_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__pureZstrutils_u123)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI j_1;
	nimfr_("nimIdentNormalize", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(299, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(300);	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		nimln_(301);		goto BeforeRet_;
	}
LA3_: ;
	nimln_(302);	if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
	}
	nimPrepareStrMutationV2((&result));
	if (((NI)0) < 0 || ((NI)0) >= s_p0.len){ raiseIndexError2(((NI)0),s_p0.len-1); goto BeforeRet_;
	}
	result.p->data[((NI)0)] = s_p0.p->data[((NI)0)];
	nimln_(303);	j_1 = ((NI)1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_47;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(304, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_51;
				if (!(res_1 <= colontmp_)) goto LA7;
				nimlf_(304, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				nimln_(305);				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(s_p0.p->data[i_1])) >= ((NU8)(65)) && ((NU8)(s_p0.p->data[i_1])) <= ((NU8)(90)))) goto LA10_;
					nimln_(306);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (nimAddInt(((NU8)(s_p0.p->data[i_1])), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); goto BeforeRet_;
					};
					if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48), ((NI)0), ((NI)255)); goto BeforeRet_;
					}
					result.p->data[j_1] = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48))));
					nimln_(307);					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49);
				}
				goto LA8_;
LA10_: ;
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
					nimln_(308);					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!!(((NU8)(s_p0.p->data[i_1]) == (NU8)(95)))) goto LA13_;
					nimln_(309);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[j_1] = s_p0.p->data[i_1];
					nimln_(310);					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
				}
				goto LA8_;
LA13_: ;
LA8_: ;
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51);
			} LA7: ;
		}
	}
	nimlf_(311, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	{
		if (!!((j_1 == s_p0.len))) goto LA17_;
		if ((j_1) < ((NI)0) || (j_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(j_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (j_1));
	}
LA17_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A, parseEnum__pureZunittest_u499)(NimStringV2 s_p0) {
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A result;
	NimStringV2 colontmpD_;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A colontmpD__2;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A colontmpD__3;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A colontmpD__4;
NIM_BOOL* nimErr_;
	nimfr_("parseEnum", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0;
	colontmpD__3 = (tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0;
	colontmpD__4 = (tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0;
	nimlf_(1307, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	nimln_(1324);	nimlf_(28, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/enumutils.nim");	colontmpD_ = nimIdentNormalize__pureZstrutils_u123(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_53)) goto LA2_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)) goto LA3_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_57)) goto LA4_;
	goto LA5_;
	LA2_: ;
	{
		nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");		colontmpD__2 = ((tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0);
		result = colontmpD__2;
	}
	goto LA6_;
	LA3_: ;
	{
		nimln_(132);		colontmpD__3 = ((tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)1);
		result = colontmpD__3;
	}
	goto LA6_;
	LA4_: ;
	{
		nimln_(133);		colontmpD__4 = ((tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)2);
		result = colontmpD__4;
	}
	goto LA6_;
	LA5_: ;
	{
		tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T11_;
		NimStringV2 T12_;
		T11_ = NIM_NIL;
		T11_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
		(*T11_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
		(*T11_).Sup.Sup.name = "ValueError";
		nimlf_(78, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/enumutils.nim");		T12_.len = 0; T12_.p = NIM_NIL;
		T12_ = rawNewString(s_p0.len + 20);
appendString((&T12_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_59);
appendString((&T12_), s_p0);
		(*T11_).Sup.Sup.message = T12_;
		(*T11_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(77);		raiseExceptionEx((Exception*)T11_, "ValueError", "parseEnum", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/enumutils.nim", 77);
goto LA1_;
	}
LA6_: ;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u256)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2) {
	NIM_BOOL result;
	NIM_BOOL colontmpD_;
	NIM_BOOL colontmpD__2;
	NI length_1;
	nimfr_("substrEq", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result = (NIM_BOOL)0;
	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NIM_BOOL)0;
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	length_1 = substr_p2.len;
	nimln_(372);	{
		NI i_1;
		if (!(((NI)0) < length_1)) goto LA3_;
		nimln_(373);		i_1 = ((NI)0);
		{
			nimln_(374);			while (1) {
				NIM_BOOL T7_;
				NIM_BOOL T8_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_60;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_61;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_62;
				T7_ = (NIM_BOOL)0;
				T8_ = (NIM_BOOL)0;
				T8_ = (i_1 < length_1);
				if (!(T8_)) goto LA9_;
				if (nimAddInt(pos_p1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_60)) { raiseOverflow(); goto BeforeRet_;
				};
				T8_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_60) < s_p0.len);
LA9_: ;
				T7_ = T8_;
				if (!(T7_)) goto LA10_;
				if (nimAddInt(pos_p1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61),s_p0.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= substr_p2.len){ raiseIndexError2(i_1,substr_p2.len-1); goto BeforeRet_;
				}
				T7_ = ((NU8)(s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)]) == (NU8)(substr_p2.p->data[i_1]));
LA10_: ;
				if (!T7_) goto LA6;
				nimln_(375);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_62)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_62);
			} LA6: ;
		}
		nimln_(376);		colontmpD_ = (i_1 == length_1);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(377);		colontmpD__2 = NIM_FALSE;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("split", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(418);	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym69__1;
		NI colontmpD_;
		NI colontmpD__2;
		NI sepLen_1;
		NI lastX60gensym41__1;
		NI splitsX60gensym41__1;
		xX60gensym69__1.len = 0; xX60gensym69__1.p = NIM_NIL;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(536);		{
			if (!(sep_p1.len == ((NI)0))) goto LA5_;
			colontmpD_ = ((NI)1);
			sepLen_1 = colontmpD_;
		}
		goto LA3_;
LA5_: ;
		{
			nimln_(537);			colontmpD__2 = sep_p1.len;
			sepLen_1 = colontmpD__2;
		}
LA3_: ;
		nimln_(390);		lastX60gensym41__1 = ((NI)0);
		nimln_(391);		splitsX60gensym41__1 = maxsplit_p2;
		{
			nimln_(538);			while (1) {
				NI firstX60gensym41__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_64;
				NimStringV2 T19_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_65;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_66;
				nimln_(393);				if (!(lastX60gensym41__1 <= s_p0.len)) goto LA9;
				nimln_(394);				firstX60gensym41__1 = lastX60gensym41__1;
				{
					nimln_(395);					while (1) {
						NIM_BOOL T12_;
						NIM_BOOL T14_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_63;
						T12_ = (NIM_BOOL)0;
						T12_ = (lastX60gensym41__1 < s_p0.len);
						if (!(T12_)) goto LA13_;
						T14_ = (NIM_BOOL)0;
						T14_ = substrEq__pureZstrutils_u256(s_p0, lastX60gensym41__1, sep_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
						T12_ = !(T14_);
LA13_: ;
						if (!T12_) goto LA11;
						nimln_(396);						if (nimAddInt(lastX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63);
					} LA11: ;
				}
				nimln_(397);				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA17_;
					lastX60gensym41__1 = s_p0.len;
				}
LA17_: ;
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				nimlf_(804, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				nimln_(398);				if (nimSubInt(lastX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_64)) { raiseOverflow(); goto LA2_;
				};
				nimln_(804);				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = substr__system_u9118(s_p0, firstX60gensym41__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_64));
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___system_u2731((&xX60gensym69__1), T19_);
				nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				blitTmp_1 = xX60gensym69__1;
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqwasMoved___system_u2722((&xX60gensym69__1));
				nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				add__stdZenumutils_u70((&result), blitTmp_1);
				nimln_(399);				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA22_;
					goto LA8;
				}
LA22_: ;
				nimln_(400);				if (nimSubInt(splitsX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_65)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_65);
				nimln_(401);				if (nimAddInt(lastX60gensym41__1, sepLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_66)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_66);
			} LA9: ;
		} LA8: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (xX60gensym69__1.p && !(xX60gensym69__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym69__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("split", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(418, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym67__1;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		xX60gensym67__1.len = 0; xX60gensym67__1.p = NIM_NIL;
		nimln_(390);		lastX60gensym34__1 = ((NI)0);
		nimln_(391);		splitsX60gensym34__1 = maxsplit_p2;
		{
			nimln_(450);			while (1) {
				NI firstX60gensym34__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_68;
				NimStringV2 T13_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_69;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_70;
				nimln_(393);				if (!(lastX60gensym34__1 <= s_p0.len)) goto LA4;
				nimln_(394);				firstX60gensym34__1 = lastX60gensym34__1;
				{
					nimln_(395);					while (1) {
						NIM_BOOL T7_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_67;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym34__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= s_p0.len){ raiseIndexError2(lastX60gensym34__1,s_p0.len-1); goto LA2_;
						}
						T7_ = !(((NU8)(s_p0.p->data[lastX60gensym34__1]) == (NU8)(sep_p1)));
LA8_: ;
						if (!T7_) goto LA6;
						nimln_(396);						if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_67)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_67);
					} LA6: ;
				}
				nimln_(397);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA11_;
					lastX60gensym34__1 = s_p0.len;
				}
LA11_: ;
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				nimlf_(760, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				nimln_(398);				if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_68)) { raiseOverflow(); goto LA2_;
				};
				nimln_(760);				T13_.len = 0; T13_.p = NIM_NIL;
				T13_ = substr__system_u9118(s_p0, firstX60gensym34__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_68));
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___system_u2731((&xX60gensym67__1), T13_);
				nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				blitTmp_1 = xX60gensym67__1;
				nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqwasMoved___system_u2722((&xX60gensym67__1));
				nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				add__stdZenumutils_u70((&result), blitTmp_1);
				nimln_(399);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA16_;
					goto LA3;
				}
LA16_: ;
				nimln_(400);				if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_69)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69);
				nimln_(401);				if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_70)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_70);
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (xX60gensym67__1.p && !(xX60gensym67__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym67__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym144__1;
	NI sLenX60gensym144__1;
	NI iX60gensym144__1;
	nimfr_("startsWith", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	nimlf_(1647, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result = NIM_FALSE;
	nimlf_(56, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");	prefixLenX60gensym144__1 = prefix_p1.len;
	nimln_(57);	sLenX60gensym144__1 = s_p0.len;
	nimln_(58);	iX60gensym144__1 = ((NI)0);
	{
		nimlf_(1648, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_71;
			nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");			{
				if (!(prefixLenX60gensym144__1 <= iX60gensym144__1)) goto LA5_;
				nimlf_(1634, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			nimln_(61);			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym144__1 <= iX60gensym144__1);
				if (T9_) goto LA10_;
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= s_p0.len){ raiseIndexError2(iX60gensym144__1,s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= prefix_p1.len){ raiseIndexError2(iX60gensym144__1,prefix_p1.len-1); goto BeforeRet_;
				}
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym144__1]) == (NU8)(prefix_p1.p->data[iX60gensym144__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				nimlf_(1634, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				nimlf_(61, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			nimln_(62);			if (nimAddInt(iX60gensym144__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_71)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym144__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_71);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1) {
	NIM_BOOL result;
	NI suffixLenX60gensym151__1;
	NI sLenX60gensym151__1;
	NI iX60gensym151__1;
	NI jX60gensym151__1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_72;
	nimfr_("endsWith", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	nimlf_(1676, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result = NIM_FALSE;
	nimlf_(65, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");	suffixLenX60gensym151__1 = suffix_p1.len;
	nimln_(66);	sLenX60gensym151__1 = s_p0.len;
	nimln_(67);	iX60gensym151__1 = ((NI)0);
	nimln_(68);	if (nimSubInt(sLenX60gensym151__1, suffixLenX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_72)) { raiseOverflow(); goto BeforeRet_;
	};
	jX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_72);
	{
		nimln_(69);		while (1) {
			NIM_BOOL T3_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_73;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_74;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_76;
			T3_ = (NIM_BOOL)0;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_73)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = (((NI)0) <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_73));
			if (!(T3_)) goto LA4_;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_74)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_74) < sLenX60gensym151__1);
LA4_: ;
			if (!T3_) goto LA2;
			nimln_(70);			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_75;
				if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_75)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75),s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym151__1 < 0 || iX60gensym151__1 >= suffix_p1.len){ raiseIndexError2(iX60gensym151__1,suffix_p1.len-1); goto BeforeRet_;
				}
				if (!!(((NU8)(s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75)]) == (NU8)(suffix_p1.p->data[iX60gensym151__1])))) goto LA7_;
				nimlf_(1663, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				nimlf_(70, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA7_: ;
			nimln_(71);			if (nimAddInt(iX60gensym151__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_76)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_76);
		} LA2: ;
	}
	nimlf_(1677, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	{
		nimlf_(72, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");		if (!(suffixLenX60gensym151__1 <= iX60gensym151__1)) goto LA11_;
		nimlf_(1663, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		nimlf_(72, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/private/strimpl.nim");		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitWhitespace)(NimStringV2 s_p0, NI maxsplit_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("splitWhitespace", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(418, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym74__1;
		NI lastX60gensym59__1;
		NI splitsX60gensym59__1;
		xX60gensym74__1.len = 0; xX60gensym74__1.p = NIM_NIL;
		nimln_(404);		lastX60gensym59__1 = ((NI)0);
		nimln_(405);		splitsX60gensym59__1 = maxsplit_p1;
		nimln_(406);		{
			if (!NIM_FALSE) goto LA5_;
			failedAssertImpl__stdZassertions_u95(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78);
			if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		}
LA5_: ;
		{
			nimln_(743);			while (1) {
				NI firstX60gensym59__1;
				nimln_(407);				if (!(lastX60gensym59__1 < s_p0.len)) goto LA8;
				{
					nimln_(408);					while (1) {
						NIM_BOOL T11_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_79;
						T11_ = (NIM_BOOL)0;
						T11_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T11_)) goto LA12_;
						if (lastX60gensym59__1 < 0 || lastX60gensym59__1 >= s_p0.len){ raiseIndexError2(lastX60gensym59__1,s_p0.len-1); goto LA2_;
						}
						T11_ = (((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12)));
LA12_: ;
						if (!T11_) goto LA10;
						if (nimAddInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_79)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_79);
					} LA10: ;
				}
				nimln_(409);				firstX60gensym59__1 = lastX60gensym59__1;
				{
					nimln_(410);					while (1) {
						NIM_BOOL T15_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_80;
						T15_ = (NIM_BOOL)0;
						T15_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T15_)) goto LA16_;
						if (lastX60gensym59__1 < 0 || lastX60gensym59__1 >= s_p0.len){ raiseIndexError2(lastX60gensym59__1,s_p0.len-1); goto LA2_;
						}
						T15_ = !((((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12))));
LA16_: ;
						if (!T15_) goto LA14;
						if (nimAddInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_80)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_80);
					} LA14: ;
				}
				nimln_(411);				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_81;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_82;
					NimStringV2 T25_;
					NimStringV2 blitTmp_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_83;
					if (nimSubInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_81)) { raiseOverflow(); goto LA2_;
					};
					if (!(firstX60gensym59__1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_81))) goto LA19_;
					nimln_(412);					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA23_;
						lastX60gensym59__1 = s_p0.len;
					}
LA23_: ;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					nimlf_(929, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					nimln_(413);					if (nimSubInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_82)) { raiseOverflow(); goto LA2_;
					};
					nimln_(929);					T25_.len = 0; T25_.p = NIM_NIL;
					T25_ = substr__system_u9118(s_p0, firstX60gensym59__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_82));
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					eqsink___system_u2731((&xX60gensym74__1), T25_);
					nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					blitTmp_1 = xX60gensym74__1;
					nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					eqwasMoved___system_u2722((&xX60gensym74__1));
					nimlf_(419, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					add__stdZenumutils_u70((&result), blitTmp_1);
					nimln_(414);					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA28_;
						goto LA7;
					}
LA28_: ;
					nimln_(415);					if (nimSubInt(splitsX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_83)) { raiseOverflow(); goto LA2_;
					};
					splitsX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_83);
				}
LA19_: ;
			} LA8: ;
		} LA7: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (xX60gensym74__1.p && !(xX60gensym74__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym74__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	nimfr_("join", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(1871, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	{
		NI L_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_84;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_85;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		nimln_(1872);		if (nimSubInt(a_p0Len_0, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_84)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt(sep_p1.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_84), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_85)) { raiseOverflow(); goto BeforeRet_;
		};
		L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_85);
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			nimlf_(1873, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");			colontmp_ = (a_p0Len_0-1);
			nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_86;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_87;
					if (!(res_1 <= colontmp_)) goto LA7;
					nimlf_(1873, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(L_1, a_p0[i_1].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_86)) { raiseOverflow(); goto BeforeRet_;
					};
					L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_86);
					nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_87)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_87);
				} LA7: ;
			}
		}
		nimlf_(1874, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = rawNewString((L_1));
		nimln_(1875);		if (((NI)0) < 0 || ((NI)0) >= a_p0Len_0){ raiseIndexError2(((NI)0),a_p0Len_0-1); goto BeforeRet_;
		}
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			nimlf_(1876, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");			colontmp__2 = (a_p0Len_0-1);
			nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			res_2 = ((NI)1);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_88;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimlf_(1876, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");					i_2 = ((NI) (res_2));
					nimln_(1877);					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					nimln_(1878);					if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_88)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_88);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1880, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_90;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_92;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_93;
	nimfr_("find", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1972, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	result = ((NI)-1);
	nimln_(1973);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1984);	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_92)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_92), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_93)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_93);
	nimln_(1985);	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		nimln_(1986);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		nimln_(1987);		{
			if (!!((found_1 == 0))) goto LA12_;
			nimln_(1988);			nimln_(1960);			nimln_(1988);			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_95;
	NI skip_1;
	nimfr_("find", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(1932);	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1933);	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_95)) { raiseOverflow(); goto BeforeRet_;
	};
	subLast_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95);
	nimln_(1935);	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		nimln_(1938);		nimln_(1920);		nimln_(1938);		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(1942);	result = ((NI)-1);
	nimln_(1943);	skip_1 = start_p3;
	{
		nimln_(1945);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_96;
			NI i_1;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_99;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_100;
			if (nimSubInt(last_2, skip_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_96)) { raiseOverflow(); goto BeforeRet_;
			};
			if (!(subLast_1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_96))) goto LA11;
			nimln_(1946);			i_1 = subLast_1;
			{
				nimln_(1947);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_97;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_98;
					if (nimAddInt(skip_1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_97)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_97) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_97) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_97),s_p1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= sub_p2.len){ raiseIndexError2(i_1,sub_p2.len-1); goto BeforeRet_;
					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_97)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					nimln_(1948);					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						nimln_(1949);						nimln_(1920);						nimln_(1949);						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					nimln_(1950);					if (nimSubInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_98)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_98);
				} LA13: ;
			}
			nimln_(1951);			if (nimAddInt(skip_1, subLast_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_99)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99),s_p1.len-1); goto BeforeRet_;
			}
			if (nimAddInt(skip_1, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_100)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_100 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_100 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			skip_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_100);
		} LA11: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1905);	m_1 = sub_p1.len;
	nimln_(1906);	fill__pureZstrutils_u1634(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_101;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(1908, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_101)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_101);
		nimlf_(128, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_102;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_103;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_104;
				if (!(i_2 < colontmp_)) goto LA3;
				nimlf_(1908, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				i_1 = i_2;
				nimln_(1909);				if (i_1 < 0 || i_1 >= sub_p1.len){ raiseIndexError2(i_1,sub_p1.len-1); goto BeforeRet_;
				}
				if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_102)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_102), i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_103)) { raiseOverflow(); goto BeforeRet_;
				};
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_103);
				nimlf_(131, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_104)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_104);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1918, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI subLen_1;
NIM_BOOL* nimErr_;
	nimfr_("find", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(2032);	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_91;
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_91)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_91) < sub_p1.len)) goto LA3_;
		nimln_(2020);		nimln_(2032);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(2033);	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		nimln_(2020);		nimln_(2033);		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto BeforeRet_;
		}
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(2042);	subLen_1 = sub_p1.len;
	nimln_(2043);	{
		NIM_BOOL T11_;
		NIM_BOOL T12_;
		NI colontmpD_;
		NI colontmpD__2;
		void* found_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_94;
		T11_ = (NIM_BOOL)0;
		T12_ = (NIM_BOOL)0;
		T12_ = (last_p3 < ((NI)0));
		if (!(T12_)) goto LA13_;
		T12_ = (start_p2 < s_p0.len);
LA13_: ;
		T11_ = T12_;
		if (!(T11_)) goto LA14_;
		T11_ = !((subLen_1 == ((NI)0)));
LA14_: ;
		if (!T11_) goto LA15_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(2044);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_94)) { raiseOverflow(); goto BeforeRet_;
		};
		found_1 = memmem(((void*) ((&s_p0.p->data[start_p2]))), ((size_t) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94))), ((void*) (nimToCStringConv(sub_p1))), ((size_t) (subLen_1)));
		nimln_(2045);		{
			if (!!((found_1 == 0))) goto LA19_;
			nimln_(2046);			colontmpD_ = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			result = colontmpD_;
		}
		goto LA17_;
LA19_: ;
		{
			nimln_(2048);			colontmpD__2 = ((NI)-1);
			result = colontmpD__2;
		}
LA17_: ;
	}
	goto LA9_;
LA15_: ;
	{
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T23_;
		nimln_(2036);		nimZeroMem((void*)T23_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nsuInitNewSkipTable(sub_p1, T23_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = nsuFindStrA(T23_, s_p0, sub_p1, start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1900)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("contains", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(2190);	nimln_(2185);	nimln_(2190);	T1_ = (NI)0;
	T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toLowerAscii", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(224);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym7__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_105;
		NI res_1;
		iX60gensym7__1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(225, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_105)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_105);
		nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_106;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(239, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");				iX60gensym7__1 = ((NI) (res_1));
				nimln_(226);				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= result.len){ raiseIndexError2(iX60gensym7__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= s_p0.len){ raiseIndexError2(iX60gensym7__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToLowerAsciiChar(s_p0.p->data[iX60gensym7__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym7__1] = T4_;
				nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_106)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_106);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsSpaceAsciiChar)(NIM_CHAR c_p0) {
	NIM_BOOL result;
	nimfr_("isSpaceAscii", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");
{	nimlf_(175, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/strutils.nim");	nimln_(169);	nimln_(175);	result = (((NU8)(c_p0)) == ((NU8)(32)) || ((NU8)(c_p0)) == ((NU8)(9)) || ((NU8)(c_p0)) == ((NU8)(11)) || ((NU8)(c_p0)) == ((NU8)(13)) || ((NU8)(c_p0)) == ((NU8)(10)) || ((NU8)(c_p0)) == ((NU8)(12)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
