/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@punittest.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@punittest.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ;
typedef struct tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ_Content tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ_Content;
typedef struct tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ;
typedef struct tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg;
typedef struct tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ {
  NI len; tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ_Content* p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ {
	RootObj Sup;
};
typedef NU8 tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A;
struct tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA {
	tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ Sup;
	NIM_BOOL colorOutput;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A outputLevel;
	NIM_BOOL isInSuite;
	NIM_BOOL isInTest;
};
typedef NU16 tySet_tyEnum_Style__YiG8w1YcnwREbgNu5MQw7w;
typedef NU8 tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg;
typedef NimStringV2 tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ[2];
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
typedef NU8 tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg;
struct tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA {
	NimStringV2 suiteName;
	NimStringV2 testName;
	tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg status;
};
typedef NimStringV2 tyArray__awn6UrBeChh9cVy9ccoluuYg[5];
struct tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg {
	tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ Sup;
	tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* stream;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ testErrors;
	NF testStartTime;
	NimStringV2 testStackTrace;
};
typedef NU8 tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg;
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ_Content { NI cap; tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* data[SEQ_DECL_SIZE]; };
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv__stdZenvvars_u20)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u62)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, NimStringV2 suiteName_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u66)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u70)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u75)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u79)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u567)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, setStyle__pureZterminal_u413)(FILE* f_p0, tySet_tyEnum_Style__YiG8w1YcnwREbgNu5MQw7w style_p1);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor__pureZterminal_u509)(FILE* f_p0, tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg fg_p1, NIM_BOOL bright_p2);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes__pureZterminal_u374)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u582)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u585)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u612)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZunittest_u21)(tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg e_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u699)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u777)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeLine__pureZstreams_u231)(tyObject_StreamObj__lqelNzDzDmo6g72gK9aeqyg* s_p0, NimStringV2* args_p1, NI args_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatSingleElem)(NimStringV2 formatstr_p0, NimStringV2 a_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, xmlEscape__pureZunittest_u701)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u780)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__system_u5539)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NF, epochTime__pureZtimes_u5238)(void);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u787)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZunittest_u791)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2* y_p1, NI y_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u814)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatFloat)(NF f_p0, tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0);
static N_INLINE(NimStringV2*, X5BX5D___pureZunittest_u822)(NimStringV2* s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u870)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZunittest_u331)(tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ* dest_p0, tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA*, defaultConsoleFormatter__pureZunittest_u483)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colorOutput__pureZunittest_u479)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__pureZterminal_u635)(FILE* f_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A, parseEnum__pureZunittest_u499)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA*, newConsoleOutputFormatter__pureZunittest_u404)(tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A outputLevel_p0, NIM_BOOL colorOutput_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunittest_u458)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__stdZcmdline_u61)(void);
N_LIB_PRIVATE N_NIMCALL(void, incl__pureZunittest_u1201)(tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw* s_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__stdZcmdline_u55)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZunittest_u913)(tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw s_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter__pureZunittest_u884)(NimStringV2 suiteName_p0, NimStringV2 testName_p1, NimStringV2 filter_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5635)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob__pureZunittest_u872)(NimStringV2 matcher_p0, NimStringV2 filter_p1);
static N_INLINE(NIM_BOOL, contains__stdZprivateZospaths2_u380)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
static N_INLINE(NI, find__stdZprivateZospaths2_u385)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u78)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u81)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_2 = { 22 | NIM_STRLIT_FLAG, "NIMTEST_ABORT_ON_ERROR" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_3 = {22, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_4 = { 9 | NIM_STRLIT_FLAG, "\012[Suite] " };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_5 = {9, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_6 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_7 = {1, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_6};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_8 = {9, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_9 = { 4 | NIM_STRLIT_FLAG, "    " };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_10 = {4, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_9};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_11 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_12 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_11};
static const struct {
  NI cap; NIM_CHAR data[155+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_13 = { 155 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_14 = {155, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_13};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_15 = { 2 | NIM_STRLIT_FLAG, "  " };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_16 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_15};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_17 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_11};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_18 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_19 = {1, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_18};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_20 = { 2 | NIM_STRLIT_FLAG, "OK" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_21 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_20};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_22 = { 6 | NIM_STRLIT_FLAG, "FAILED" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_23 = {6, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_22};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_24 = { 7 | NIM_STRLIT_FLAG, "SKIPPED" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_25 = {7, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_24};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_26 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_27 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_26};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_28 = { 2 | NIM_STRLIT_FLAG, "] " };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_29 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_28};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_30 = {1, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_6};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_31 = {1, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_18};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_32 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_28};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_33 = { 22 | NIM_STRLIT_FLAG, "\011<testsuite name=\"$1\">" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_34 = {22, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_33};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_35 = { 4 | NIM_STRLIT_FLAG, "&lt;" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_36 = {4, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_35};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_37 = { 4 | NIM_STRLIT_FLAG, "&gt;" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_38 = {4, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_37};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_39 = { 5 | NIM_STRLIT_FLAG, "&amp;" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_40 = {5, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_39};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_41 = { 6 | NIM_STRLIT_FLAG, "&quot;" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_42 = {6, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_41};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_43 = { 6 | NIM_STRLIT_FLAG, "&apos;" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_44 = {6, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_43};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_45 = { 2 | NIM_STRLIT_FLAG, "&#" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_46 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_45};
static const struct {
  NI cap; NIM_CHAR data[158+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_47 = { 158 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_48 = {158, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_47};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_49 = { 32 | NIM_STRLIT_FLAG, "\011\011<testcase name=\"$#\" time=\"$#\">" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_50 = {32, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_49};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_52 = { 11 | NIM_STRLIT_FLAG, "<skipped />" };
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_54 = { 43 | NIM_STRLIT_FLAG, "The test failed without outputting an error" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_55 = {43, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_54};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_56 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_11};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_59 = {1, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_6};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_61 = { 33 | NIM_STRLIT_FLAG, "\011\011\011<error message=\"$#\">$#</error>" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_62 = {33, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_61};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_63 = { 30 | NIM_STRLIT_FLAG, "\011\011\011<system-err>$#</system-err>" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_64 = {30, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_63};
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_65 = { 37 | NIM_STRLIT_FLAG, "\011\011\011<failure message=\"$#\">$#</failure>" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_66 = {37, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_65};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_68 = { 13 | NIM_STRLIT_FLAG, "\011\011</testcase>" };
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_70 = { 13 | NIM_STRLIT_FLAG, "\011</testsuite>" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_71 = { 4 | NIM_STRLIT_FLAG, "auto" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_72 = {4, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_71};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_73 = {4, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_71};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_74 = { 2 | NIM_STRLIT_FLAG, "on" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_75 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_74};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_76 = { 3 | NIM_STRLIT_FLAG, "off" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_77 = {3, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_76};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_78 = { 13 | NIM_STRLIT_FLAG, "NIMTEST_COLOR" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_79 = {13, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_78};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_80 = {13, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_78};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_81 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_11};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_82 = { 5 | NIM_STRLIT_FLAG, "never" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_83 = {5, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_82};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_84 = { 6 | NIM_STRLIT_FLAG, "always" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_85 = {6, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_84};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_86 = { 16 | NIM_STRLIT_FLAG, "NIMTEST_NO_COLOR" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_87 = {16, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_86};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_88 = { 9 | NIM_STRLIT_FLAG, "PRINT_ALL" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_89 = {9, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_88};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_90 = { 18 | NIM_STRLIT_FLAG, "NIMTEST_OUTPUT_LVL" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_91 = {18, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_90};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_92 = {18, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_90};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_93 = {0, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_11};
N_LIB_PRIVATE TNimTypeV2 NTIv2__bVIcGQH9c8e6PCetdpQYkVA_;
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_96 = { 2 | NIM_STRLIT_FLAG, "::" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_97 = {2, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_96};
static const struct {
  NI cap; NIM_CHAR data[169+1];
} TM__Um3CQPZ9bILAIolZOsxNIaw_100 = { 169 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/sets.nim(272, 13) `len(s) == length` the length of the HashSet changed while iterating over it" };
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_101 = {169, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_100};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_103 = {155, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_13};
static const NimStringV2 TM__Um3CQPZ9bILAIolZOsxNIaw_104 = {155, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_13};
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__Um3CQPZ9bILAIolZOsxNIaw_51 = {{11, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_52}}
;
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__Um3CQPZ9bILAIolZOsxNIaw_67 = {{13, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_68}}
;
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__Um3CQPZ9bILAIolZOsxNIaw_69 = {{13, (NimStrPayload*)&TM__Um3CQPZ9bILAIolZOsxNIaw_70}}
;
N_LIB_PRIVATE NIM_THREADVAR tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__pureZunittest_u45;
N_LIB_PRIVATE NIM_THREADVAR tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ formatters__pureZunittest_u46;
N_LIB_PRIVATE NIM_THREADVAR tyObject_HashSet__baCF0FFSTfEJUebvvEnS9aw testsFilters__pureZunittest_u52;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL abortOnError__pureZunittest_u44;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL disabledParamFiltering__pureZunittest_u53;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static NIM_CONST NU32 TM__Um3CQPZ9bILAIolZOsxNIaw_94[3] = {3701606400, 1552182784, 1377573120};
N_LIB_PRIVATE TNimTypeV2 NTIv2__bVIcGQH9c8e6PCetdpQYkVA_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA), .align = (NI16) NIM_ALIGNOF(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA), .depth = 2, .display = TM__Um3CQPZ9bILAIolZOsxNIaw_94, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u62)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, NimStringV2 suiteName_p1) {
	nimfr_("suiteStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u66)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, NimStringV2 testName_p1) {
	nimfr_("testStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u70)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2) {
	nimfr_("failureOccurred", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u75)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1) {
	nimfr_("testEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u79)(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ* formatter_p0) {
	nimfr_("suiteEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u567)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, NimStringV2 suiteName_p1) {
NIM_BOOL* nimErr_;
	nimfr_("suiteStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(265, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		if (!(*formatter_p0).colorOutput) goto LA3_;
		nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");		setStyle__pureZterminal_u413(__stdoutp, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		setForegroundColor__pureZterminal_u509(__stdoutp, ((tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)34), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(266, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");		write__stdZsyncio_u254(__stdoutp, TM__Um3CQPZ9bILAIolZOsxNIaw_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");		resetAttributes__pureZterminal_u374(__stdoutp);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		write__stdZsyncio_u254(__stdoutp, suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(875);		resetAttributes__pureZterminal_u374(__stdoutp);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(880);		write__stdZsyncio_u254(__stdoutp, TM__Um3CQPZ9bILAIolZOsxNIaw_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T6_;
		nimlf_(267, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");		T6_[0] = TM__Um3CQPZ9bILAIolZOsxNIaw_8;
		T6_[1] = suiteName_p1;
		echoBinSafe(T6_, 2);
	}
LA1_: ;
	nimln_(269);	(*formatter_p0).isInSuite = NIM_TRUE;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u582)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, NimStringV2 testName_p1) {
	nimfr_("testStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	nimln_(272);	(*formatter_p0).isInTest = NIM_TRUE;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u585)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2) {
	NimStringV2 prefix_1;
	NimStringV2 T6_;
NIM_BOOL* nimErr_;
	nimfr_("failureOccurred", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	prefix_1.len = 0; prefix_1.p = NIM_NIL;
	nimln_(276);	{
		tyArray__YgExxhfgKcesA5EOUj1MOA T5_;
		if (!(((NI)0) < stackTrace_p2.len)) goto LA3_;
		nimln_(277);		T5_[0] = stackTrace_p2;
		echoBinSafe(T5_, 1);
	}
LA3_: ;
	T6_.len = 0; T6_.p = NIM_NIL;
	nimln_(278);	{
		if (!(*formatter_p0).isInSuite) goto LA9_;
		prefix_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_10;
	}
	goto LA7_;
LA9_: ;
	{
		prefix_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_12;
	}
LA7_: ;
	{
		NimStringV2* msg_1;
		NI i_1;
		NI L_1;
		NI T13_;
		msg_1 = (NimStringV2*)0;
		nimlf_(249, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T13_ = checkpoints_p1.len;
		L_1 = T13_;
		{
			nimln_(251);			while (1) {
				tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T16_;
				if (!(i_1 < L_1)) goto LA15;
				nimlf_(279, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");				if (i_1 < 0 || i_1 >= checkpoints_p1.len){ raiseIndexError2(i_1,checkpoints_p1.len-1); goto BeforeRet_;
				}
				msg_1 = (&checkpoints_p1.p->data[i_1]);
				nimln_(280);				T16_[0] = prefix_1;
				T16_[1] = (*msg_1);
				echoBinSafe(T16_, 2);
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T19_;
					T19_ = checkpoints_p1.len;
					if (!!((T19_ == L_1))) goto LA20_;
					failedAssertImpl__stdZassertions_u95(TM__Um3CQPZ9bILAIolZOsxNIaw_14);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA20_: ;
			} LA15: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZunittest_u21)(tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)0):
	{
		result = TM__Um3CQPZ9bILAIolZOsxNIaw_21;
	}
	break;
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)1):
	{
		result = TM__Um3CQPZ9bILAIolZOsxNIaw_23;
	}
	break;
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)2):
	{
		result = TM__Um3CQPZ9bILAIolZOsxNIaw_25;
	}
	break;
	default:
	{
		result = TM__Um3CQPZ9bILAIolZOsxNIaw_27;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u612)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1) {
NIM_BOOL* nimErr_;
	nimfr_("testEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(283, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	(*formatter_p0).isInTest = NIM_FALSE;
	nimln_(285);	{
		NIM_BOOL T3_;
		NIM_BOOL T5_;
		NimStringV2 prefix_1;
		NimStringV2 T9_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*formatter_p0).outputLevel == ((tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)2)));
		if (!(T3_)) goto LA4_;
		nimln_(286);		T5_ = (NIM_BOOL)0;
		T5_ = ((*formatter_p0).outputLevel == ((tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0));
		if (T5_) goto LA6_;
		T5_ = ((*testResult_p1).status == ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)1));
LA6_: ;
		T3_ = T5_;
LA4_: ;
		if (!T3_) goto LA7_;
		prefix_1.len = 0; prefix_1.p = NIM_NIL;
		T9_.len = 0; T9_.p = NIM_NIL;
		nimln_(287);		{
			if (!(((NI)0) < (*testResult_p1).suiteName.len)) goto LA12_;
			prefix_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_16;
		}
		goto LA10_;
LA12_: ;
		{
			prefix_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_17;
		}
LA10_: ;
		nimln_(291);		{
			tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg colontmpD_;
			tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg colontmpD__2;
			tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg colontmpD__3;
			NimStringV2 colontmpD__4;
			tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg color_1;
			if (!(*formatter_p0).colorOutput) goto LA17_;
			colontmpD_ = (tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)0;
			colontmpD__2 = (tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)0;
			colontmpD__3 = (tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)0;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			nimln_(292);			switch ((*testResult_p1).status) {
			case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)0):
			{
				nimln_(293);				colontmpD_ = ((tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)32);
				color_1 = colontmpD_;
			}
			break;
			case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)1):
			{
				nimln_(294);				colontmpD__2 = ((tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)31);
				color_1 = colontmpD__2;
			}
			break;
			case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)2):
			{
				nimln_(295);				colontmpD__3 = ((tyEnum_ForegroundColor__cSggpFutm9al0coG5XotnOg)33);
				color_1 = colontmpD__3;
			}
			break;
			default: __builtin_unreachable();
			}
			nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");			setStyle__pureZterminal_u413(__stdoutp, 1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			setForegroundColor__pureZterminal_u509(__stdoutp, color_1, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			write__stdZsyncio_u254(__stdoutp, prefix_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimlf_(296, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			write__stdZsyncio_u254(__stdoutp, TM__Um3CQPZ9bILAIolZOsxNIaw_19);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");			nimlf_(296, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			colontmpD__4 = dollar___pureZunittest_u21((*testResult_p1).status);
			nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");			write__stdZsyncio_u254(__stdoutp, colontmpD__4);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimlf_(296, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			write__stdZsyncio_u254(__stdoutp, TM__Um3CQPZ9bILAIolZOsxNIaw_29);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimlf_(865, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/terminal.nim");			resetAttributes__pureZterminal_u374(__stdoutp);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			write__stdZsyncio_u254(__stdoutp, (*testResult_p1).testName);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimln_(875);			resetAttributes__pureZterminal_u374(__stdoutp);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			nimln_(880);			write__stdZsyncio_u254(__stdoutp, TM__Um3CQPZ9bILAIolZOsxNIaw_30);
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			{
				LA19_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA15_;
LA17_: ;
		{
			NimStringV2 colontmpD__5;
			tyArray__awn6UrBeChh9cVy9ccoluuYg T27_;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			nimlf_(299, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			T27_[0] = prefix_1;
			T27_[1] = TM__Um3CQPZ9bILAIolZOsxNIaw_31;
			nimln_(288);			colontmpD__5 = dollar___pureZunittest_u21((*testResult_p1).status);
			T27_[2] = colontmpD__5;
			T27_[3] = TM__Um3CQPZ9bILAIolZOsxNIaw_32;
			T27_[4] = (*testResult_p1).testName;
			echoBinSafe(T27_, 5);
			{
				LA26_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
	}
LA7_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u699)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* formatter_p0) {
	nimfr_("suiteEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	nimlf_(304, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	(*formatter_p0).isInSuite = NIM_FALSE;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, xmlEscape__pureZunittest_u701)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("xmlEscape", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(307);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString((s_p0.len));
	{
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		c_1 = (NIM_CHAR)0;
		nimlf_(267, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(268);		L_1 = s_p0.len;
		{
			nimln_(269);			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				nimlf_(308, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				c_1 = s_p0.p->data[i_1];
				nimln_(309);				switch (((NU8)(c_1))) {
				case 60:
				{
					nimln_(310);					prepareAdd((&result), 4);
appendString((&result), TM__Um3CQPZ9bILAIolZOsxNIaw_36);
				}
				break;
				case 62:
				{
					nimln_(311);					prepareAdd((&result), 4);
appendString((&result), TM__Um3CQPZ9bILAIolZOsxNIaw_38);
				}
				break;
				case 38:
				{
					nimln_(312);					prepareAdd((&result), 5);
appendString((&result), TM__Um3CQPZ9bILAIolZOsxNIaw_40);
				}
				break;
				case 34:
				{
					nimln_(313);					prepareAdd((&result), 6);
appendString((&result), TM__Um3CQPZ9bILAIolZOsxNIaw_42);
				}
				break;
				case 39:
				{
					nimln_(314);					prepareAdd((&result), 6);
appendString((&result), TM__Um3CQPZ9bILAIolZOsxNIaw_44);
				}
				break;
				default:
				{
					nimln_(316);					{
						NimStringV2 colontmpD_;
						NimStringV2 colontmpD__2;
						NimStringV2 T14_;
						if (!(((NU8)(c_1)) < ((NI)32))) goto LA12_;
						colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
						colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
						nimln_(317);						T14_.len = 0; T14_.p = NIM_NIL;
						colontmpD_ = dollar___systemZdollars_u14(((NU8)(c_1)));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						T14_ = rawNewString(colontmpD_.len + 3);
appendString((&T14_), TM__Um3CQPZ9bILAIolZOsxNIaw_46);
appendString((&T14_), colontmpD_);
appendChar((&T14_), 59);
						colontmpD__2 = T14_;
						prepareAdd((&result), colontmpD__2.len + 0);
appendString((&result), colontmpD__2);
						nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					}
					goto LA10_;
LA12_: ;
					{
						nimlf_(319, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");						nimAddCharV1((&result), c_1);
					}
LA10_: ;
				}
				break;
				}
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(272);				{
					if (!!((s_p0.len == L_1))) goto LA18_;
					failedAssertImpl__stdZassertions_u95(TM__Um3CQPZ9bILAIolZOsxNIaw_48);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA18_: ;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u777)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, NimStringV2 suiteName_p1) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyArray__YgExxhfgKcesA5EOUj1MOA T2_;
NIM_BOOL* nimErr_;
	nimfr_("suiteStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(342, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	colontmpD_ = xmlEscape__pureZunittest_u701(suiteName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = nsuFormatSingleElem(TM__Um3CQPZ9bILAIolZOsxNIaw_34, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD__2;
	writeLine__pureZstreams_u231((*formatter_p0).stream, T2_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u780)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, NimStringV2 testName_p1) {
	NF T1_;
NIM_BOOL* nimErr_;
	nimfr_("testStarted", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(345, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	setLen__system_u5539((&(*formatter_p0).testErrors), ((NI)0));
	nimln_(346);	setLengthStrV2((&(*formatter_p0).testStackTrace), ((NI)0));
	nimln_(347);	T1_ = (NF)0;
	T1_ = epochTime__pureZtimes_u5238();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*formatter_p0).testStartTime = T1_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u787)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2) {
	nimfr_("failureOccurred", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	nimln_(353);	add__pureZunittest_u791((&(*formatter_p0).testErrors), ((checkpoints_p1).p) ? (checkpoints_p1.p->data) : NIM_NIL, checkpoints_p1.len);
	nimln_(354);	{
		if (!(((NI)0) < stackTrace_p2.len)) goto LA3_;
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqcopy___system_u2725((&(*formatter_p0).testStackTrace), stackTrace_p2);
	}
LA3_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NimStringV2*, X5BX5D___pureZunittest_u822)(NimStringV2* s_p0, NI s_p0Len_0, NI i_p1) {
	NimStringV2* result;
	NI TM__Um3CQPZ9bILAIolZOsxNIaw_53;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");
{	result = (NimStringV2*)0;
	nimlf_(30, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");	if (nimSubInt(s_p0Len_0, i_p1, &TM__Um3CQPZ9bILAIolZOsxNIaw_53)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_53) < 0 || (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_53) >= s_p0Len_0){ raiseIndexError2((NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_53),s_p0Len_0-1); goto BeforeRet_;
	}
	result = (&s_p0[(NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_53)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u814)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0, tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p1) {
	NimStringV2 timeStr_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NF time_1;
	NF T2_;
	tyArray__YgExxhfgKcesA5EOUj1MOA T3_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T4_;
NIM_BOOL* nimErr_;
	nimfr_("testEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	timeStr_1.len = 0; timeStr_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(358, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	T2_ = (NF)0;
	T2_ = epochTime__pureZtimes_u5238();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	time_1 = ((NF)(T2_) - (NF)((*formatter_p0).testStartTime));
	nimln_(359);	timeStr_1 = nsuformatFloat(time_1, ((tyEnum_FloatFormatMode__zRahyLLprqMZGJakxSQicg)1), ((NI)8), 46);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(360);	nimln_(361);	colontmpD_ = xmlEscape__pureZunittest_u701((*testResult_p1).testName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T4_[0] = colontmpD_;
	T4_[1] = timeStr_1;
	nimln_(360);	colontmpD__2 = nsuFormatOpenArray(TM__Um3CQPZ9bILAIolZOsxNIaw_50, T4_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[0] = colontmpD__2;
	writeLine__pureZstreams_u231((*formatter_p0).stream, T3_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(362);	switch ((*testResult_p1).status) {
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)0):
	{
	}
	break;
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)2):
	{
		nimln_(366);		writeLine__pureZstreams_u231((*formatter_p0).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_51, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	break;
	case ((tyEnum_TestStatus__0Ey5XaYaI9cwpR9bTHFM3XUg)1):
	{
		NimStringV2 failureMsg_1;
		NimStringV2 errs_1;
		NimStringV2 T9_;
		failureMsg_1.len = 0; failureMsg_1.p = NIM_NIL;
		errs_1.len = 0; errs_1.p = NIM_NIL;
		T9_.len = 0; T9_.p = NIM_NIL;
		nimln_(368);		{
			NIM_BOOL T12_;
			NI T14_;
			NimStringV2* T17_;
			T12_ = (NIM_BOOL)0;
			T12_ = (((NI)0) < (*formatter_p0).testStackTrace.len);
			if (!(T12_)) goto LA13_;
			nimln_(369);			T14_ = (*formatter_p0).testErrors.len;
			T12_ = (((NI)0) < T14_);
LA13_: ;
			if (!T12_) goto LA15_;
			nimln_(368);			nimln_(370);			T17_ = (NimStringV2*)0;
			T17_ = X5BX5D___pureZunittest_u822((((*formatter_p0).testErrors).p) ? ((*formatter_p0).testErrors.p->data) : NIM_NIL, (*formatter_p0).testErrors.len, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			failureMsg_1 = xmlEscape__pureZunittest_u701((*T17_));
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		}
		goto LA10_;
LA15_: ;
		{
			NI T19_;
			nimln_(371);			T19_ = (*formatter_p0).testErrors.len;
			if (!(((NI)0) < T19_)) goto LA20_;
			nimln_(368);			nimln_(372);			if (((NI)0) < 0 || ((NI)0) >= (*formatter_p0).testErrors.len){ raiseIndexError2(((NI)0),(*formatter_p0).testErrors.len-1); goto LA8_;
			}
			failureMsg_1 = xmlEscape__pureZunittest_u701((*formatter_p0).testErrors.p->data[((NI)0)]);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		}
		goto LA10_;
LA20_: ;
		{
			nimln_(368);			nimln_(373);			failureMsg_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_55;
		}
LA10_: ;
		nimln_(375);		errs_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_56;
		nimln_(376);		{
			NI T25_;
			NI colontmpD__3;
			NI colontmpD__4;
			NI colontmpD__5;
			NI colontmpD__6;
			NI startIdx_1;
			NI endIdx_1;
			T25_ = (*formatter_p0).testErrors.len;
			if (!(((NI)1) < T25_)) goto LA26_;
			colontmpD__3 = (NI)0;
			colontmpD__4 = (NI)0;
			colontmpD__5 = (NI)0;
			colontmpD__6 = (NI)0;
			nimln_(377);			{
				if (!(((NI)0) < (*formatter_p0).testStackTrace.len)) goto LA30_;
				colontmpD__3 = ((NI)0);
				startIdx_1 = colontmpD__3;
			}
			goto LA28_;
LA30_: ;
			{
				colontmpD__4 = ((NI)1);
				startIdx_1 = colontmpD__4;
			}
LA28_: ;
			nimln_(378);			{
				NI T37_;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_57;
				if (!(((NI)0) < (*formatter_p0).testStackTrace.len)) goto LA35_;
				nimln_(379);				T37_ = (*formatter_p0).testErrors.len;
				if (nimSubInt(T37_, ((NI)2), &TM__Um3CQPZ9bILAIolZOsxNIaw_57)) { raiseOverflow(); goto LA8_;
				};
				colontmpD__5 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_57);
				endIdx_1 = colontmpD__5;
			}
			goto LA33_;
LA35_: ;
			{
				NI T39_;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_58;
				nimln_(380);				T39_ = (*formatter_p0).testErrors.len;
				if (nimSubInt(T39_, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_58)) { raiseOverflow(); goto LA8_;
				};
				colontmpD__6 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_58);
				endIdx_1 = colontmpD__6;
			}
LA33_: ;
			{
				NI errIdx_1;
				NI res_1;
				errIdx_1 = (NI)0;
				nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				res_1 = startIdx_1;
				{
					nimln_(97);					while (1) {
						NimStringV2 colontmpD__7;
						NI TM__Um3CQPZ9bILAIolZOsxNIaw_60;
						if (!(res_1 <= endIdx_1)) goto LA42;
						colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
						nimlf_(382, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");						errIdx_1 = ((NI) (res_1));
						nimln_(383);						{
							if (!(((NI)0) < errs_1.len)) goto LA45_;
							nimln_(384);							prepareAdd((&errs_1), 1);
appendString((&errs_1), TM__Um3CQPZ9bILAIolZOsxNIaw_59);
						}
LA45_: ;
						nimln_(385);						if (errIdx_1 < 0 || errIdx_1 >= (*formatter_p0).testErrors.len){ raiseIndexError2(errIdx_1,(*formatter_p0).testErrors.len-1); goto LA8_;
						}
						colontmpD__7 = xmlEscape__pureZunittest_u701((*formatter_p0).testErrors.p->data[errIdx_1]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
						prepareAdd((&errs_1), colontmpD__7.len + 0);
appendString((&errs_1), colontmpD__7);
						nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");						if (nimAddInt(res_1, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_60)) { raiseOverflow(); goto LA8_;
						};
						res_1 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_60);
						nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
					} LA42: ;
				}
			}
		}
LA26_: ;
		nimlf_(387, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");		{
			NimStringV2 colontmpD__8;
			NimStringV2 colontmpD__9;
			tyArray__YgExxhfgKcesA5EOUj1MOA T52_;
			tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T53_;
			if (!(((NI)0) < (*formatter_p0).testStackTrace.len)) goto LA49_;
			colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
			colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
			nimln_(388);			T53_[0] = failureMsg_1;
			nimln_(389);			colontmpD__8 = xmlEscape__pureZunittest_u701((*formatter_p0).testStackTrace);
			if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
			T53_[1] = colontmpD__8;
			nimln_(388);			colontmpD__9 = nsuFormatOpenArray(TM__Um3CQPZ9bILAIolZOsxNIaw_62, T53_, 2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
			T52_[0] = colontmpD__9;
			writeLine__pureZstreams_u231((*formatter_p0).stream, T52_, 1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
			nimln_(390);			{
				NimStringV2 colontmpD__10;
				tyArray__YgExxhfgKcesA5EOUj1MOA T59_;
				if (!(((NI)0) < errs_1.len)) goto LA56_;
				colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
				nimln_(391);				colontmpD__10 = nsuFormatSingleElem(TM__Um3CQPZ9bILAIolZOsxNIaw_64, errs_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
				T59_[0] = colontmpD__10;
				writeLine__pureZstreams_u231((*formatter_p0).stream, T59_, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
				{
					LA58_:;
				}
				{
					nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
			}
LA56_: ;
			{
				LA51_:;
			}
			{
				if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
				if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		}
		goto LA47_;
LA49_: ;
		{
			NimStringV2 colontmpD__11;
			tyArray__YgExxhfgKcesA5EOUj1MOA T66_;
			tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T67_;
			colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
			nimlf_(393, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			T67_[0] = failureMsg_1;
			T67_[1] = errs_1;
			colontmpD__11 = nsuFormatOpenArray(TM__Um3CQPZ9bILAIolZOsxNIaw_66, T67_, 2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA65_;
			T66_[0] = colontmpD__11;
			writeLine__pureZstreams_u231((*formatter_p0).stream, T66_, 1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA65_;
			{
				LA65_:;
			}
			{
				nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__11.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		}
LA47_: ;
		{
			LA8_:;
		}
		{
			if (errs_1.p && !(errs_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(errs_1.p);
}
			if (failureMsg_1.p && !(failureMsg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(failureMsg_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	break;
	default: __builtin_unreachable();
	}
	nimlf_(396, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	writeLine__pureZstreams_u231((*formatter_p0).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_67, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (timeStr_1.p && !(timeStr_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(timeStr_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u870)(tyObject_JUnitOutputFormattercolonObjectType___I7rN4jxuliQJ2O5Mz2Nvwg* formatter_p0) {
NIM_BOOL* nimErr_;
	nimfr_("suiteEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(399, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	writeLine__pureZstreams_u231((*formatter_p0).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_69, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colorOutput__pureZunittest_u479)(void) {
	NIM_BOOL result;
	NimStringV2 color_1;
NIM_BOOL* nimErr_;
	nimfr_("colorOutput", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	color_1.len = 0; color_1.p = NIM_NIL;
	nimlf_(231, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	color_1 = TM__Um3CQPZ9bILAIolZOsxNIaw_72;
	nimln_(232);	if (eqStrings(color_1, TM__Um3CQPZ9bILAIolZOsxNIaw_73)) goto LA1_;
	if (eqStrings(color_1, TM__Um3CQPZ9bILAIolZOsxNIaw_75)) goto LA2_;
	if (eqStrings(color_1, TM__Um3CQPZ9bILAIolZOsxNIaw_77)) goto LA3_;
	goto LA4_;
	LA1_: ;
	{
		nimln_(234);		result = isatty__pureZterminal_u635(__stdoutp);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA5_;
	LA2_: ;
	{
		nimln_(236);		result = NIM_TRUE;
	}
	goto LA5_;
	LA3_: ;
	{
		nimln_(237);		result = NIM_FALSE;
	}
	goto LA5_;
	LA4_: ;
	{
		nimln_(238);		raiseAssert__stdZassertions_u28(color_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	nimln_(241);	{
		NIM_BOOL T12_;
		NimStringV2 colorEnv_1;
		T12_ = (NIM_BOOL)0;
		T12_ = existsEnv__stdZenvvars_u20(TM__Um3CQPZ9bILAIolZOsxNIaw_79);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T12_) goto LA13_;
		colorEnv_1.len = 0; colorEnv_1.p = NIM_NIL;
		nimln_(243);		colorEnv_1 = getEnv__stdZenvvars_u15(TM__Um3CQPZ9bILAIolZOsxNIaw_80, TM__Um3CQPZ9bILAIolZOsxNIaw_81);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(244);		{
			if (!eqStrings(colorEnv_1, TM__Um3CQPZ9bILAIolZOsxNIaw_83)) goto LA17_;
			nimln_(245);			result = NIM_FALSE;
		}
		goto LA15_;
LA17_: ;
		{
			nimln_(246);			if (!eqStrings(colorEnv_1, TM__Um3CQPZ9bILAIolZOsxNIaw_85)) goto LA20_;
			nimln_(247);			result = NIM_TRUE;
		}
		goto LA15_;
LA20_: ;
LA15_: ;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colorEnv_1.p && !(colorEnv_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colorEnv_1.p);
}
	}
	goto LA10_;
LA13_: ;
	{
		NIM_BOOL T23_;
		nimlf_(248, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");		T23_ = (NIM_BOOL)0;
		T23_ = existsEnv__stdZenvvars_u20(TM__Um3CQPZ9bILAIolZOsxNIaw_87);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T23_) goto LA24_;
		nimln_(250);		result = NIM_FALSE;
	}
	goto LA10_;
LA24_: ;
LA10_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA*, newConsoleOutputFormatter__pureZunittest_u404)(tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A outputLevel_p0, NIM_BOOL colorOutput_p1) {
	tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* result;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A colontmpD_;
	NIM_BOOL colontmpD__2;
	tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* T1_;
	nimfr_("newConsoleOutputFormatter", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	colontmpD_ = (tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A)0;
	colontmpD__2 = (NIM_BOOL)0;
	nimln_(225);	T1_ = NIM_NIL;
	T1_ = (tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA*) nimNewObj(sizeof(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA), NIM_ALIGNOF(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA));
	(*T1_).Sup.Sup.m_type = (&NTIv2__bVIcGQH9c8e6PCetdpQYkVA_);
	nimln_(226);	colontmpD_ = outputLevel_p0;
	(*T1_).outputLevel = colontmpD_;
	nimln_(227);	colontmpD__2 = colorOutput_p1;
	(*T1_).colorOutput = colontmpD__2;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA*, defaultConsoleFormatter__pureZunittest_u483)(void) {
	tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* result;
	NIM_BOOL colorOutput_1;
	tyEnum_OutputLevel__1bY4dNQHXaDi9aS1CkdI16A outputLevel_1;
NIM_BOOL* nimErr_;
	nimfr_("defaultConsoleFormatter", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(253);	colorOutput_1 = colorOutput__pureZunittest_u479();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(254);	nimln_(255);	outputLevel_1 = parseEnum__pureZunittest_u499(TM__Um3CQPZ9bILAIolZOsxNIaw_89);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(257);	{
		NIM_BOOL T3_;
		NimStringV2 colontmpD_;
		T3_ = (NIM_BOOL)0;
		T3_ = existsEnv__stdZenvvars_u20(TM__Um3CQPZ9bILAIolZOsxNIaw_91);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(259);		nimln_(260);		nimln_(259);		colontmpD_ = getEnv__stdZenvvars_u15(TM__Um3CQPZ9bILAIolZOsxNIaw_92, TM__Um3CQPZ9bILAIolZOsxNIaw_93);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimln_(260);		outputLevel_1 = parseEnum__pureZunittest_u499(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimlf_(260, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	result = newConsoleOutputFormatter__pureZunittest_u404(outputLevel_1, colorOutput_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(518, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunittest_u458)(tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized__pureZunittest_u1169)(void) {
NIM_BOOL* nimErr_;
	nimfr_("ensureInitialized", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(449, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		NI T3_;
		tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ T6_;
		tyObject_ConsoleOutputFormattercolonObjectType___bVIcGQH9c8e6PCetdpQYkVA* T7_;
		T3_ = formatters__pureZunittest_u46.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(221);		nimln_(450);		T6_.len = 0; T6_.p = NIM_NIL;
		T6_.len = 1; T6_.p = (tySequence__1dr9bYt1E0XMVfXh9bM6eOpQ_Content*) newSeqPayload(1, sizeof(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ*), NIM_ALIGNOF(tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ*));
		T7_ = NIM_NIL;
		T7_ = defaultConsoleFormatter__pureZunittest_u483();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZunittest_u458(T7_); goto BeforeRet_;}
		T6_.p->data[0] = &T7_->Sup;
		nimln_(221);		eqsink___pureZunittest_u331((&formatters__pureZunittest_u46), T6_);
	}
LA4_: ;
	nimln_(452);	{
		if (!!(disabledParamFiltering__pureZunittest_u53)) goto LA10_;
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			nimlf_(455, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");			colontmp_ = paramCount__stdZcmdline_u61();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			res_1 = ((NI)1);
			{
				nimln_(97);				while (1) {
					NimStringV2 colontmpD_;
					NI TM__Um3CQPZ9bILAIolZOsxNIaw_95;
					if (!(res_1 <= colontmp_)) goto LA14;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimlf_(455, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");					i_1 = ((NI) (res_1));
					nimln_(456);					colontmpD_ = paramStr__stdZcmdline_u55(i_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					incl__pureZunittest_u1201((&testsFilters__pureZunittest_u52), colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_95)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_95);
					nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				} LA14: ;
			}
		}
	}
LA10_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
	nimlf_(27, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
static N_INLINE(NI, find__stdZprivateZospaths2_u385)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NI result;
	nimfr_("find", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
{	nimlf_(1918, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NI)0);
	{
		NIM_CHAR i_1;
		NI i_2;
		i_1 = (NIM_CHAR)0;
		nimlf_(28, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(29);			while (1) {
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_98;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1919, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = a_p0[i_2];
				nimln_(1920);				{
					if (!((NU8)(i_1) == (NU8)(item_p1))) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1921);				if (nimAddInt(result, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_98)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_98);
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(1922, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZprivateZospaths2_u380)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
{	nimln_(1936);	nimln_(1924);	nimln_(1936);	T1_ = (NI)0;
	T1_ = find__stdZprivateZospaths2_u385(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob__pureZunittest_u872)(NimStringV2 matcher_p0, NimStringV2 filter_p1) {
	NIM_BOOL result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ beforeAndAfter_1;
	NIM_BOOL T20_;
NIM_BOOL* nimErr_;
	nimfr_("glob", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	beforeAndAfter_1.len = 0; beforeAndAfter_1.p = NIM_NIL;
	nimlf_(403, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		if (!(filter_p1.len == ((NI)0))) goto LA4_;
		nimln_(404);		nimln_(401);		nimln_(404);		result = NIM_TRUE;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(beforeAndAfter_1);
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(406, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = contains__stdZprivateZospaths2_u380(((filter_p1).p) ? (filter_p1.p->data) : NIM_NIL, filter_p1.len, 42);
		if (!!(T8_)) goto LA9_;
		nimln_(407);		nimln_(401);		nimln_(407);		result = eqStrings(matcher_p0, filter_p1);
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(beforeAndAfter_1);
		goto BeforeRet_;
	}
LA9_: ;
	nimlf_(409, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	beforeAndAfter_1 = nsuSplitChar(filter_p1, 42, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(410);	{
		NI T13_;
		T13_ = beforeAndAfter_1.len;
		if (!(T13_ == ((NI)1))) goto LA14_;
		nimln_(412);		nimln_(401);		nimln_(412);		if (((NI)0) < 0 || ((NI)0) >= beforeAndAfter_1.len){ raiseIndexError2(((NI)0),beforeAndAfter_1.len-1); goto LA1_;
		}
		result = nsuStartsWith(matcher_p0, beforeAndAfter_1.p->data[((NI)0)]);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(beforeAndAfter_1);
		goto BeforeRet_;
	}
LA14_: ;
	nimlf_(414, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		NI TM__Um3CQPZ9bILAIolZOsxNIaw_99;
		if (nimSubInt(filter_p1.len, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_99)) { raiseOverflow(); goto LA1_;
		};
		if (!(matcher_p0.len < (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_99))) goto LA18_;
		nimln_(415);		nimln_(401);		nimln_(415);		result = NIM_FALSE;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(beforeAndAfter_1);
		goto BeforeRet_;
	}
LA18_: ;
	nimlf_(417, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	nimln_(401);	nimln_(417);	T20_ = (NIM_BOOL)0;
	if (((NI)0) < 0 || ((NI)0) >= beforeAndAfter_1.len){ raiseIndexError2(((NI)0),beforeAndAfter_1.len-1); goto LA1_;
	}
	T20_ = nsuStartsWith(matcher_p0, beforeAndAfter_1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (!(T20_)) goto LA21_;
	if (((NI)1) < 0 || ((NI)1) >= beforeAndAfter_1.len){ raiseIndexError2(((NI)1),beforeAndAfter_1.len-1); goto LA1_;
	}
	T20_ = nsuEndsWith(matcher_p0, beforeAndAfter_1.p->data[((NI)1)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
LA21_: ;
	result = T20_;
	nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqdestroy___system_u5635(beforeAndAfter_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_u5635(beforeAndAfter_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter__pureZunittest_u884)(NimStringV2 suiteName_p0, NimStringV2 testName_p1, NimStringV2 filter_p2) {
	NIM_BOOL result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ suiteAndTestFilters_1;
	NIM_BOOL T15_;
NIM_BOOL* nimErr_;
	nimfr_("matchFilter", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	suiteAndTestFilters_1.len = 0; suiteAndTestFilters_1.p = NIM_NIL;
	nimlf_(421, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		if (!(filter_p2.len == 0)) goto LA4_;
		nimln_(422);		nimln_(420);		nimln_(422);		result = NIM_TRUE;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(suiteAndTestFilters_1);
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(423, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		if (!eqStrings(testName_p1, filter_p2)) goto LA8_;
		nimln_(425);		nimln_(420);		nimln_(425);		result = NIM_TRUE;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(suiteAndTestFilters_1);
		goto BeforeRet_;
	}
LA8_: ;
	nimlf_(426, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	suiteAndTestFilters_1 = nsuSplitString(filter_p2, TM__Um3CQPZ9bILAIolZOsxNIaw_97, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(428);	{
		NI T12_;
		NimStringV2 testFilter_1;
		T12_ = suiteAndTestFilters_1.len;
		if (!(T12_ == ((NI)1))) goto LA13_;
		testFilter_1.len = 0; testFilter_1.p = NIM_NIL;
		nimln_(430);		if (((NI)0) < 0 || ((NI)0) >= suiteAndTestFilters_1.len){ raiseIndexError2(((NI)0),suiteAndTestFilters_1.len-1); goto LA1_;
		}
		testFilter_1 = suiteAndTestFilters_1.p->data[((NI)0)];
		nimln_(431);		nimln_(420);		nimln_(431);		result = glob__pureZunittest_u872(testName_p1, testFilter_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		eqdestroy___system_u5635(suiteAndTestFilters_1);
		goto BeforeRet_;
	}
LA13_: ;
	nimlf_(433, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	nimln_(420);	nimln_(433);	T15_ = (NIM_BOOL)0;
	if (((NI)0) < 0 || ((NI)0) >= suiteAndTestFilters_1.len){ raiseIndexError2(((NI)0),suiteAndTestFilters_1.len-1); goto LA1_;
	}
	T15_ = glob__pureZunittest_u872(suiteName_p0, suiteAndTestFilters_1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (!(T15_)) goto LA16_;
	nimln_(434);	if (((NI)1) < 0 || ((NI)1) >= suiteAndTestFilters_1.len){ raiseIndexError2(((NI)1),suiteAndTestFilters_1.len-1); goto LA1_;
	}
	T15_ = glob__pureZunittest_u872(testName_p1, suiteAndTestFilters_1.p->data[((NI)1)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
LA16_: ;
	result = T15_;
	nimlf_(2219, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqdestroy___system_u5635(suiteAndTestFilters_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_u5635(suiteAndTestFilters_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun__pureZunittest_u894)(NimStringV2 currentSuiteName_p0, NimStringV2 testName_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("shouldRun", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(439, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = len__pureZunittest_u913(testsFilters__pureZunittest_u52);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(440);		nimln_(436);		nimln_(440);		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA4_: ;
	{
		NimStringV2 f_1;
		NI length_1;
		f_1.len = 0; f_1.p = NIM_NIL;
		nimlf_(268, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/sets.nim");		length_1 = len__pureZunittest_u913(testsFilters__pureZunittest_u52);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		{
			NI h_1;
			NI colontmp_;
			NI T9_;
			NI res_1;
			h_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			nimlf_(269, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/sets.nim");			T9_ = (testsFilters__pureZunittest_u52.data.len-1);
			colontmp_ = T9_;
			nimlf_(96, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__Um3CQPZ9bILAIolZOsxNIaw_102;
					if (!(res_1 <= colontmp_)) goto LA11;
					nimlf_(269, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/sets.nim");					h_1 = ((NI) (res_1));
					nimln_(270);					{
						NIM_BOOL T14_;
						if (h_1 < 0 || h_1 >= testsFilters__pureZunittest_u52.data.len){ raiseIndexError2(h_1,testsFilters__pureZunittest_u52.data.len-1); goto LA7_;
						}
						T14_ = (NIM_BOOL)0;
						T14_ = isFilled__pureZcollectionsZsets_u39(testsFilters__pureZunittest_u52.data.p->data[h_1].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
						if (!T14_) goto LA15_;
						nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");						if (h_1 < 0 || h_1 >= testsFilters__pureZunittest_u52.data.len){ raiseIndexError2(h_1,testsFilters__pureZunittest_u52.data.len-1); goto LA7_;
						}
						eqcopy___system_u2725((&f_1), testsFilters__pureZunittest_u52.data.p->data[h_1].Field1);
						nimlf_(443, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");						{
							NIM_BOOL T19_;
							T19_ = (NIM_BOOL)0;
							T19_ = matchFilter__pureZunittest_u884(currentSuiteName_p0, testName_p1, f_1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
							if (!T19_) goto LA20_;
							nimln_(444);							nimln_(436);							nimln_(444);							result = NIM_TRUE;
							nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");							if (f_1.p && !(f_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(f_1.p);
}
							goto BeforeRet_;
						}
LA20_: ;
						nimlf_(272, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/sets.nim");						{
							NI T24_;
							T24_ = (NI)0;
							T24_ = len__pureZunittest_u913(testsFilters__pureZunittest_u52);
							if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
							if (!!((T24_ == length_1))) goto LA25_;
							failedAssertImpl__stdZassertions_u95(TM__Um3CQPZ9bILAIolZOsxNIaw_101);
							if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
						}
LA25_: ;
					}
LA15_: ;
					nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__Um3CQPZ9bILAIolZOsxNIaw_102)) { raiseOverflow(); goto LA7_;
					};
					res_1 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_102);
				} LA11: ;
			}
		}
		{
			LA7_:;
		}
		{
			nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (f_1.p && !(f_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(f_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	nimlf_(446, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	nimln_(436);	nimln_(446);	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkpoint__pureZunittest_u1665)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
	nimfr_("checkpoint", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(589);	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD_ = eqdup___system_u2728(msg_p0);
	nimlf_(589, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	add__stdZenumutils_u70((&checkpoints__pureZunittest_u45), colontmpD_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u1646)(tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* testResult_p0) {
NIM_BOOL* nimErr_;
	nimfr_("testEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	{
		tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ** formatter_1;
		NI i_1;
		NI L_1;
		NI T2_;
		formatter_1 = (tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ**)0;
		nimlf_(249, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = formatters__pureZunittest_u46.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(465, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");				if (i_1 < 0 || i_1 >= formatters__pureZunittest_u46.len){ raiseIndexError2(i_1,formatters__pureZunittest_u46.len-1); goto BeforeRet_;
				}
				formatter_1 = &formatters__pureZunittest_u46.p->data[i_1];
				nimln_(466);				testEnded__pureZunittest_u78((*formatter_1), testResult_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T7_;
					T7_ = formatters__pureZunittest_u46.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u95(TM__Um3CQPZ9bILAIolZOsxNIaw_103);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___tscoped95component_u837)(tyObject_TestResult__BCV68GC8eNlvDpJkfEDTJA* dest_p0) {
	if ((*dest_p0).testName.p && !((*dest_p0).testName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).testName.p);
}
	if ((*dest_p0).suiteName.p && !((*dest_p0).suiteName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).suiteName.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u1604)(void) {
NIM_BOOL* nimErr_;
	nimfr_("suiteEnded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
{nimErr_ = nimErrorFlag();
	{
		tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ** formatter_1;
		NI i_1;
		NI L_1;
		NI T2_;
		formatter_1 = (tyObject_OutputFormattercolonObjectType___yVyEbreI24KOsClbv9adADQ**)0;
		nimln_(249);		i_1 = ((NI)0);
		nimln_(250);		T2_ = formatters__pureZunittest_u46.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(461, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");				if (i_1 < 0 || i_1 >= formatters__pureZunittest_u46.len){ raiseIndexError2(i_1,formatters__pureZunittest_u46.len-1); goto BeforeRet_;
				}
				formatter_1 = &formatters__pureZunittest_u46.p->data[i_1];
				nimln_(462);				suiteEnded__pureZunittest_u81((*formatter_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T7_;
					T7_ = formatters__pureZunittest_u46.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u95(TM__Um3CQPZ9bILAIolZOsxNIaw_104);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpunittestdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("unittest", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");
nimErr_ = nimErrorFlag();
	nimlf_(193, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/unittest.nim");	abortOnError__pureZunittest_u44 = NIM_FALSE;
	nimln_(195);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = existsEnv__stdZenvvars_u20(TM__Um3CQPZ9bILAIolZOsxNIaw_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(197);		abortOnError__pureZunittest_u44 = NIM_TRUE;
	}
LA4_: ;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

