/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib -I/Users/nakagawa_shota/repo/valit/crown/tests -o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@puri.nim.c.o /Users/nakagawa_shota/repo/valit/crown/.nimcache_test/@puri.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, decodePercent__stdZprivateZdecode95helpers_u56)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* i_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2474)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseData__pureZuri_u134)(NimStringV2 data_p0, NI i_p1, NimStringV2* field_p2, NIM_CHAR sep_p3) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("parseData", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/uri.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(172, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/uri.nim");	result = i_p1;
	{
		nimln_(173);		while (1) {
			NIM_CHAR c_1;
			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_2;
			if (!(result < data_p0.len)) goto LA2;
			nimln_(174);			if (result < 0 || result >= data_p0.len){ raiseIndexError2(result,data_p0.len-1); goto BeforeRet_;
			}
			c_1 = data_p0.p->data[result];
			nimln_(175);			switch (((NU8)(c_1))) {
			case 37:
			{
				NIM_CHAR T4_;
				nimln_(176);				T4_ = (NIM_CHAR)0;
				T4_ = decodePercent__stdZprivateZdecode95helpers_u56(((data_p0).p) ? (data_p0.p->data) : NIM_NIL, data_p0.len, (&result));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimAddCharV1((&(*field_p2)), T4_);
			}
			break;
			case 43:
			{
				nimln_(177);				nimAddCharV1((&(*field_p2)), 32);
			}
			break;
			case 38:
			{
				nimln_(178);				goto LA1;
			}
			break;
			default:
			{
				nimln_(180);				{
					if (!((NU8)(c_1) == (NU8)(sep_p3))) goto LA10_;
					goto LA1;
				}
				goto LA8_;
LA10_: ;
				{
					nimln_(181);					if (result < 0 || result >= data_p0.len){ raiseIndexError2(result,data_p0.len-1); goto BeforeRet_;
					}
					nimAddCharV1((&(*field_p2)), data_p0.p->data[result]);
				}
LA8_: ;
			}
			break;
			}
			nimln_(182);			if (nimAddInt(result, ((NI)1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_2)) { raiseOverflow(); goto BeforeRet_;
			};
			result = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_2);
		} LA2: ;
	} LA1: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2474(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, decodeUrl__pureZuri_u100)(NimStringV2 s_p0, NIM_BOOL decodePlus_p1) {
	NimStringV2 result;
	NI i_1;
	NI j_1;
NIM_BOOL* nimErr_;
	nimfr_("decodeUrl", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/uri.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(113);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(114);	i_1 = ((NI)0);
	nimln_(115);	j_1 = ((NI)0);
	{
		nimln_(116);		while (1) {
			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_3;
			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_4;
			if (!(i_1 < s_p0.len)) goto LA2;
			nimln_(117);			if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
			}
			switch (((NU8)(s_p0.p->data[i_1]))) {
			case 37:
			{
				NIM_CHAR T4_;
				nimln_(119);				if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				T4_ = (NIM_CHAR)0;
				T4_ = decodePercent__stdZprivateZdecode95helpers_u56(((s_p0).p) ? (s_p0.p->data) : NIM_NIL, s_p0.len, (&i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[j_1] = T4_;
			}
			break;
			case 43:
			{
				nimln_(121);				{
					if (!decodePlus_p1) goto LA8_;
					nimln_(122);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[j_1] = 32;
				}
				goto LA6_;
LA8_: ;
				{
					nimln_(124);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[j_1] = s_p0.p->data[i_1];
				}
LA6_: ;
			}
			break;
			default:
			{
				nimln_(125);				if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[j_1] = s_p0.p->data[i_1];
			}
			break;
			}
			nimln_(126);			if (nimAddInt(i_1, ((NI)1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_3)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_3);
			nimln_(127);			if (nimAddInt(j_1, ((NI)1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_4)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_4);
		} LA2: ;
	}
	nimln_(128);	if ((j_1) < ((NI)0) || (j_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(j_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&result), (j_1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
